// AUTO-GENERATED by compile.cjs from pin-scene.jsx — do not edit by hand.
/* global React, THREE */
// NOTE: edit this file then run `node compile.cjs` to rebuild js/pin-scene.js.
//
// Pinned-scroll DNA journey — progress 0..4
//   0→1.5 : camera rides the horizontal helix (zoomed in, ends cut off)
//   1.5→2.5: strand rotates 90° to vertical, camera pulls back
//   2.5→3.5: strand slides right
//   3.5→4  : hold

const PinScene = ({
  progress
}) => {
  const mountRef = React.useRef(null);
  const pRef = React.useRef(progress);
  React.useEffect(() => {
    pRef.current = progress;
  }, [progress]);
  React.useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;
    const LOW = typeof window !== "undefined" && window.__QUALITY__ === "low";
    const REDUCED = typeof window !== "undefined" && window.__REDUCED_MOTION__;
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(55, 1, 0.1, 600);
    camera.position.set(0, 0, 6);
    const renderer = new THREE.WebGLRenderer({
      antialias: !LOW,
      alpha: true,
      powerPreference: "high-performance"
    });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, LOW ? 1 : 2));
    mount.appendChild(renderer.domElement);
    const resize = () => {
      const {
        clientWidth: w,
        clientHeight: h
      } = mount;
      renderer.setSize(w, h);
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
    };
    resize();
    const ro = new ResizeObserver(resize);
    ro.observe(mount);
    const clamp01 = x => Math.max(0, Math.min(1, x));
    const ss = (a, b, x) => {
      const t = clamp01((x - a) / (b - a));
      return t * t * (3 - 2 * t);
    };
    const disposables = [];
    const track = x => {
      disposables.push(x);
      return x;
    };

    // ── DNA GROUP — starts horizontal ────────────────────────────────────────
    const dnaGroup = new THREE.Group();
    dnaGroup.rotation.z = Math.PI / 2; // helix long-axis along world X
    scene.add(dnaGroup);
    const glbMats = [];
    let glbMixer = null,
      glbMixer2 = null;
    let surfHalfH = 11,
      surfRad = 5;
    const applyHolo = root => {
      let n = 0;
      root.traverse(obj => {
        if (!obj.isMesh) return;
        n++;
        const mat = new THREE.MeshBasicMaterial({
          color: 0x00ccff,
          transparent: false,
          side: THREE.DoubleSide,
          depthWrite: true
        });
        obj.material = mat;
        glbMats.push(mat);
        disposables.push(mat);
      });
      console.log("[pin-scene] holo applied to", n, "meshes");
    };
    if (typeof THREE.GLTFLoader !== "undefined") {
      new THREE.GLTFLoader().load("assets/models/dna_hologram.glb", gltf => {
        const model = gltf.scene || gltf.scenes[0];
        model.position.set(0, 0, 0);
        model.rotation.set(0, 0, 0);
        model.scale.set(1, 1, 1);
        model.updateMatrixWorld(true);

        // Orient longest axis to Y
        const b0 = new THREE.Box3().setFromObject(model);
        const sz0 = b0.getSize(new THREE.Vector3());
        const mx0 = Math.max(sz0.x, sz0.y, sz0.z);
        if (sz0.x === mx0) model.rotation.z = Math.PI / 2;else if (sz0.z === mx0) model.rotation.x = -Math.PI / 2;
        model.updateMatrixWorld(true);

        // Scale so longest dimension = TARGET_H, then center
        const b1 = new THREE.Box3().setFromObject(model);
        const sz1 = b1.getSize(new THREE.Vector3());
        const TARGET_H = 26;
        const s = Math.max(sz1.x, sz1.y, sz1.z) > 0.0001 ? TARGET_H / Math.max(sz1.x, sz1.y, sz1.z) : 1;
        model.scale.setScalar(s);
        model.updateMatrixWorld(true);
        const b2 = new THREE.Box3().setFromObject(model);
        model.position.sub(b2.getCenter(new THREE.Vector3()));
        model.updateMatrixWorld(true);
        const b3 = new THREE.Box3().setFromObject(model);
        const sz3 = b3.getSize(new THREE.Vector3());
        surfHalfH = sz3.y / 2;
        surfRad = Math.max(sz3.x, sz3.z) / 2 + 2;
        console.log("[pin-scene] size:", sz3.x.toFixed(1), sz3.y.toFixed(1), sz3.z.toFixed(1));
        applyHolo(model);
        dnaGroup.add(model);

        // Second strand skipped on low-quality devices (saves draw calls + animation cost)
        if (!LOW) {
          const model2 = model.clone(true);
          model2.position.set(0, -sz3.y, 0);
          applyHolo(model2);
          dnaGroup.add(model2);
          if (gltf.animations && gltf.animations.length > 0) {
            glbMixer2 = new THREE.AnimationMixer(model2);
            const action2 = glbMixer2.clipAction(gltf.animations[0]);
            action2.setLoop(THREE.LoopRepeat, Infinity);
            action2.play();
          }
        }
        if (gltf.animations && gltf.animations.length > 0) {
          glbMixer = new THREE.AnimationMixer(model);
          const action = glbMixer.clipAction(gltf.animations[0]);
          action.setLoop(THREE.LoopRepeat, Infinity);
          action.play();
        }
      }, xhr => {
        if (xhr.total) console.log("[pin-scene] GLB", Math.round(xhr.loaded / xhr.total * 100) + "%");
      }, err => console.error("[pin-scene] GLB error:", err));
    } else {
      console.warn("[pin-scene] THREE.GLTFLoader not found");
    }
    const dnaAnchors = [{
      id: "BB",
      title: "Sugar-Phosphate Backbone",
      subtitle: "Phosphodiester · 2 nm diameter",
      pIn: 2.8,
      pOut: 3.2,
      x: 72,
      y: 18
    }, {
      id: "MG",
      title: "Major Groove",
      subtitle: "22 Å wide · protein landing pad",
      pIn: 3.0,
      pOut: 3.5,
      x: 68,
      y: 42
    }, {
      id: "BP",
      title: "Base Pair",
      subtitle: "A·T × 2 bonds · G·C × 3 bonds",
      pIn: 3.2,
      pOut: 3.7,
      x: 14,
      y: 56
    }, {
      id: "mG",
      title: "Minor Groove",
      subtitle: "12 Å wide · 7.5 Å deep",
      pIn: 3.5,
      pOut: 4.0,
      x: 18,
      y: 78
    }];

    // ── STARS ────────────────────────────────────────────────────────────────
    const starLayers = [];
    const makeStarLayer = (count, zNear, zFar, sz, baseColor) => {
      const pos = new Float32Array(count * 3),
        col = new Float32Array(count * 3);
      const r = (baseColor >> 16 & 0xff) / 255,
        g = (baseColor >> 8 & 0xff) / 255,
        b = (baseColor & 0xff) / 255;
      for (let i = 0; i < count; i++) {
        pos[i * 3] = (Math.random() - 0.5) * 36;
        pos[i * 3 + 1] = (Math.random() - 0.5) * 20;
        pos[i * 3 + 2] = zNear - Math.random() * (zFar - zNear);
        const k = 0.7 + Math.random() * 0.3;
        col[i * 3] = r * k;
        col[i * 3 + 1] = g * k;
        col[i * 3 + 2] = b * k;
      }
      const geo = track(new THREE.BufferGeometry());
      geo.setAttribute("position", new THREE.BufferAttribute(pos, 3));
      geo.setAttribute("color", new THREE.BufferAttribute(col, 3));
      const mat = track(new THREE.PointsMaterial({
        vertexColors: true,
        size: sz,
        transparent: true,
        opacity: 0.9,
        blending: THREE.AdditiveBlending,
        depthWrite: false
      }));
      scene.add(new THREE.Points(geo, mat));
      starLayers.push({
        mat
      });
    };
    makeStarLayer(LOW ? 80 : 500, -8, -20, 0.03, 0x8090c8);
    makeStarLayer(LOW ? 30 : 200, -4, -10, 0.05, 0xb890e0);
    makeStarLayer(LOW ? 10 : 80, -1, -5, 0.08, 0xffffff);

    // ── ANIMATION LOOP ────────────────────────────────────────────────────────
    let visible = true;
    const vio = new IntersectionObserver(([e]) => {
      visible = e.isIntersecting;
    }, {
      threshold: 0
    });
    vio.observe(mount);
    let raf,
      last = performance.now();

    // Strand animation timing (generous scroll ranges = slower, more deliberate)
    const ROT_START = 1.6;
    const ROT_END = 2.8;
    const SLIDE_START = 3.1;
    const SLIDE_END = 4.0;
    const loop = t => {
      const dt = Math.min(0.05, (t - last) / 1000);
      last = t;
      if (!visible) {
        raf = requestAnimationFrame(loop);
        return;
      }
      const p = pRef.current;
      if (glbMixer) glbMixer.update(dt);
      if (glbMixer2) glbMixer2.update(dt);

      // No passive Y rotation — strand orientation fully controlled by scroll
      dnaGroup.rotation.y = 0;

      // Z: horizontal (π/2) → vertical (0), smooth over ROT_START→ROT_END
      dnaGroup.rotation.z = Math.PI / 2 * (1 - ss(ROT_START, ROT_END, p));

      // X slide right after rotation
      dnaGroup.position.x = ss(SLIDE_START, SLIDE_END, p) * 8;

      // ── Camera ──────────────────────────────────────────────────────────
      // Two modes blended by rideBlend (0 = skateboard ride, 1 = glide):
      //
      // RIDE: camera spirals tightly around the horizontal strand while
      //       traveling along its X length — very close, helix-banking feel.
      //
      // GLIDE: single parametric formula — position is (0, localY, 9) in strand
      //        local space, transformed by strand's current Z rotation angle,
      //        so it follows the model as it rotates. Zero discontinuities.
      {
        const rideBlend = ss(ROT_START, ROT_END, p); // 0 during ride → 1 after rotation

        // ── Ride mode — tight drone sweep, very close to the strand ──
        const rideT = clamp01(p / ROT_START);
        const helixAng = (1 - rideT) * Math.PI / 4; // 45°→0°: swoop from above to front
        const droneFar = 6; // start close
        const droneNear = 4.5; // end very close
        const droneDist = droneFar + (droneNear - droneFar) * rideT;
        const ridePos = new THREE.Vector3(surfHalfH * (-0.85 + rideT * 0.85),
        // left end of strand → center
        Math.sin(helixAng) * droneDist, Math.cos(helixAng) * droneDist);

        // ── Glide mode ──
        // glideZ eases from droneNear → 9, so transition is seamless and final pose unchanged
        const glideZ = droneNear + (9 - droneNear) * ss(ROT_START, 4, p);
        const localT = clamp01(p / 4);
        const localY = surfHalfH * (0.28 - 0.72 * localT);
        const rotZ = dnaGroup.rotation.z;
        const dnaX = dnaGroup.position.x;
        const glidePos = new THREE.Vector3(-localY * Math.sin(rotZ) + dnaX * 0.18, localY * Math.cos(rotZ), glideZ);
        camera.position.lerpVectors(ridePos, glidePos, rideBlend);
        camera.up.set(0, 1, 0);

        // Look slightly ahead along X during ride; toward DNA center during glide
        const rideLook = ridePos.x + surfHalfH * 0.3;
        const glideLook = dnaX * 0.45;
        camera.lookAt(rideLook * (1 - rideBlend) + glideLook * rideBlend, 0, 0);
      }
      scene.updateMatrixWorld(true);
      camera.updateMatrixWorld();
      camera.matrixWorldInverse.copy(camera.matrixWorld).invert();

      // Labels during vertical phase only
      const labels = [];
      if (p > ROT_END) {
        for (const a of dnaAnchors) {
          const fade = ss(a.pIn, a.pIn + 0.2, p) * (1 - ss(a.pOut - 0.1, a.pOut, p));
          if (fade > 0.02) labels.push({
            id: a.id,
            title: a.title,
            subtitle: a.subtitle,
            x: a.x,
            y: a.y,
            fade
          });
        }
      }
      window.dispatchEvent(new CustomEvent("pin-labels-update", {
        detail: labels
      }));
      const tsec = t * 0.001;
      for (let li = 0; li < starLayers.length; li++) {
        const L = starLayers[li];
        const k = 0.75 + 0.25 * Math.sin(tsec * (0.6 + li * 0.25) + li * 1.3);
        L.mat.opacity = (li === starLayers.length - 1 ? 0.9 : 0.65) * k;
      }
      renderer.render(scene, camera);
      raf = requestAnimationFrame(loop);
    };
    if (REDUCED) {
      renderer.render(scene, camera);
    } else {
      raf = requestAnimationFrame(loop);
    }
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      vio.disconnect();
      renderer.dispose();
      disposables.forEach(d => {
        try {
          d.dispose && d.dispose();
        } catch (e) {}
      });
      if (renderer.domElement.parentNode === mount) mount.removeChild(renderer.domElement);
    };
  }, []);
  return /*#__PURE__*/React.createElement("div", {
    ref: mountRef,
    style: {
      position: "absolute",
      inset: 0
    }
  });
};

// ---------- LABEL OVERLAY ----------
const PinLabels = () => {
  const [labels, setLabels] = React.useState([]);
  React.useEffect(() => {
    const onUpdate = e => setLabels(e.detail);
    window.addEventListener("pin-labels-update", onUpdate);
    return () => window.removeEventListener("pin-labels-update", onUpdate);
  }, []);
  return /*#__PURE__*/React.createElement("div", {
    className: "pin-labels"
  }, labels.map(L => /*#__PURE__*/React.createElement("div", {
    key: L.id,
    className: "pin-label",
    style: {
      left: `${L.x}%`,
      top: `${L.y}%`,
      opacity: L.fade
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-label-dot"
  }), /*#__PURE__*/React.createElement("div", {
    className: "pin-label-line"
  }), /*#__PURE__*/React.createElement("div", {
    className: "pin-label-box"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-label-id"
  }, L.id), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    className: "pin-label-title"
  }, L.title), /*#__PURE__*/React.createElement("div", {
    className: "pin-label-sub"
  }, L.subtitle))))));
};
window.PinScene = PinScene;
window.PinLabels = PinLabels;
