// AUTO-GENERATED by compile.cjs from pin-scene.jsx — do not edit by hand.
/* global React, THREE */
// NOTE: this file is JSX source. If you edit it, re-run `node compile.cjs`
// to regenerate js/pin-scene.js — the browser loads the compiled .js directly.
//
// Pinned-scroll anatomy journey (graphics demo, not a claim about medical expertise).
// Six chapters mapped across progress 0..6:
//   0-1: eukaryotic cell overview — membrane, nucleus, mitochondria, ER, ribosomes
//   1-2: zoom into the nucleus; cell fades out, DNA helix fades in
//   2-3: helix → focus on one ladder rung
//   3-4: rung splits into labeled Adenine / Thymine halves (real cylindrical ladder rungs)
//   4-5: zoom further into a single nucleotide — phosphate, sugar, base labeled
//   5-6: reassemble back to the full double helix
//
// Every rung is a real 3D cylinder (not a line), wired between the two backbone strands.

const PinScene = ({
  progress
}) => {
  const mountRef = React.useRef(null);
  const pRef = React.useRef(progress);
  React.useEffect(() => {
    pRef.current = progress;
  }, [progress]);
  React.useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;
    const LOW = typeof window !== "undefined" && window.__QUALITY__ === "low";
    const REDUCED = typeof window !== "undefined" && window.__REDUCED_MOTION__;
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(38, 1, 0.05, 400);
    camera.position.set(0, 0, 6);
    const renderer = new THREE.WebGLRenderer({
      antialias: !LOW,
      alpha: true,
      powerPreference: "high-performance"
    });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, LOW ? 1.25 : 2));
    mount.appendChild(renderer.domElement);
    const resize = () => {
      const {
        clientWidth: w,
        clientHeight: h
      } = mount;
      renderer.setSize(w, h, false);
      camera.aspect = w / h;
      camera.updateProjectionMatrix();
    };
    resize();
    const ro = new ResizeObserver(resize);
    ro.observe(mount);
    const clamp01 = x => Math.max(0, Math.min(1, x));
    const ss = (a, b, x) => {
      const t = clamp01((x - a) / (b - a));
      return t * t * (3 - 2 * t);
    };
    const setOpacity = (mat, v) => {
      if (mat) {
        mat.opacity = v;
        mat.visible = v > 0.01;
      }
    };
    const disposables = [];
    const track = x => {
      disposables.push(x);
      return x;
    };

    // ==========================================================
    //   CELL GROUP
    //   ---------------------------------------------------------
    //   TWEAK ME — cell color palette (hex colors). To change the
    //   look, edit these. Designed to evoke immunofluorescence
    //   microscopy staining while matching the site palette.
    // ==========================================================
    const CELL_COLORS = {
      cyto: 0x2a1840,
      // cytoplasm deep violet glow
      membrane: 0x5eb5ff,
      // plasma membrane — cyan
      membraneWire: 0x8bd4ff,
      // phospholipid bilayer lines
      bilayerDots: 0xc8eaff,
      // phospholipid head particles
      nucleus: 0x4060e8,
      // DAPI-like deep blue
      nucleusWire: 0x7aa0ff,
      // nuclear envelope wire
      nucleolus: 0x2038a8,
      // dense nucleolus core
      chromatin: 0xb8c8ff,
      // chromatin strand highlight
      nuclearPore: 0xd0e0ff,
      // pores studding the envelope
      mitoOuter: 0xff6a48,
      // MitoTracker orange-red
      mitoWire: 0xffaa80,
      // mitochondrial cristae
      er: 0x67e8c5,
      // ER-tracker mint/green
      erWire: 0xb8ffe4,
      // ER membrane wire
      golgi: 0xffc14d,
      // Golgi apparatus — warm yellow
      golgiWire: 0xffe0a0,
      // Golgi wire
      ribosomes: 0xe879f9,
      // ribosomes — bright magenta
      vesicles: 0xffd080,
      // transport vesicles
      cytoskeleton: 0x9080a8 // microtubule lines
    };
    const cellGroup = new THREE.Group();
    scene.add(cellGroup);

    // Cytoplasm glow — very faint warm fill + faint outer wireframe
    const cytoGeo = track(new THREE.SphereGeometry(2.4, 32, 32));
    const cytoMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.cyto,
      transparent: true,
      opacity: 0.14,
      depthWrite: false,
      side: THREE.BackSide
    }));
    cellGroup.add(new THREE.Mesh(cytoGeo, cytoMat));
    const cytoWireMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.cyto,
      wireframe: true,
      transparent: true,
      opacity: 0.09
    }));
    cellGroup.add(new THREE.Mesh(cytoGeo, cytoWireMat));

    // Plasma membrane — translucent sphere + wireframe (phospholipid bilayer look)
    const memGeo = track(new THREE.SphereGeometry(2.5, 52, 52));
    const memMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.membrane,
      transparent: true,
      opacity: 0.10,
      depthWrite: false
    }));
    cellGroup.add(new THREE.Mesh(memGeo, memMat));
    const memWireMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.membraneWire,
      wireframe: true,
      transparent: true,
      opacity: 0.22
    }));
    cellGroup.add(new THREE.Mesh(memGeo, memWireMat));

    // Phospholipid bilayer: points studded along the membrane surface (both layers)
    const bilayerN = LOW ? 200 : 600;
    const bilayerGeo = track(new THREE.BufferGeometry());
    const bilayerPos = new Float32Array(bilayerN * 3);
    for (let i = 0; i < bilayerN; i++) {
      // Two layers — inner at 2.44, outer at 2.56 — gives a real bilayer thickness
      const r = (Math.random() < 0.5 ? 2.44 : 2.56) + (Math.random() - 0.5) * 0.04;
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(2 * Math.random() - 1);
      bilayerPos[i * 3] = r * Math.sin(phi) * Math.cos(theta);
      bilayerPos[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta);
      bilayerPos[i * 3 + 2] = r * Math.cos(phi);
    }
    bilayerGeo.setAttribute("position", new THREE.BufferAttribute(bilayerPos, 3));
    const bilayerMat = track(new THREE.PointsMaterial({
      color: CELL_COLORS.bilayerDots,
      size: 0.032,
      transparent: true,
      opacity: 0.75,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    }));
    cellGroup.add(new THREE.Points(bilayerGeo, bilayerMat));

    // Nucleus — deep blue sphere + wireframe envelope + internal chromatin strands
    const nucleusGroup = new THREE.Group();
    cellGroup.add(nucleusGroup);
    const nucGeo = track(new THREE.SphereGeometry(0.95, 42, 42));
    const nucMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.nucleus,
      transparent: true,
      opacity: 0.55,
      depthWrite: false
    }));
    nucleusGroup.add(new THREE.Mesh(nucGeo, nucMat));
    const nucWireMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.nucleusWire,
      wireframe: true,
      transparent: true,
      opacity: 0.4
    }));
    nucleusGroup.add(new THREE.Mesh(nucGeo, nucWireMat));

    // Nucleolus
    const nucleolusGeo = track(new THREE.SphereGeometry(0.32, 20, 20));
    const nucleolusMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.nucleolus,
      transparent: true,
      opacity: 0.85
    }));
    const nucleolus = new THREE.Mesh(nucleolusGeo, nucleolusMat);
    nucleolus.position.set(0.2, -0.1, 0.25);
    nucleusGroup.add(nucleolus);
    const nucleolusWireMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.nucleusWire,
      wireframe: true,
      transparent: true,
      opacity: 0.5
    }));
    const nucleolusWire = new THREE.Mesh(nucleolusGeo, nucleolusWireMat);
    nucleolusWire.position.copy(nucleolus.position);
    nucleusGroup.add(nucleolusWire);

    // Chromatin — 3 curved lines coiling inside the nucleus (tiny DNA hint)
    const chromatinMats = [];
    for (let ci = 0; ci < 3; ci++) {
      const pts = [];
      const turns = 2 + ci;
      for (let t = 0; t <= 64; t++) {
        const u = t / 64;
        const a = u * Math.PI * 2 * turns + ci * 2;
        const r = 0.7 - u * 0.15;
        pts.push(new THREE.Vector3(Math.cos(a) * r + ci * 0.1 - 0.1, (u - 0.5) * 1.4, Math.sin(a) * r * 0.7));
      }
      const g = track(new THREE.BufferGeometry().setFromPoints(pts));
      const m = track(new THREE.LineBasicMaterial({
        color: CELL_COLORS.chromatin,
        transparent: true,
        opacity: 0.5
      }));
      chromatinMats.push(m);
      nucleusGroup.add(new THREE.Line(g, m));
    }

    // Nuclear pores — small bright dots studding the envelope
    const poreCount = LOW ? 18 : 30;
    const poreGeo = track(new THREE.BufferGeometry());
    const porePos = new Float32Array(poreCount * 3);
    for (let i = 0; i < poreCount; i++) {
      const theta = Math.random() * Math.PI * 2;
      const phi = Math.acos(2 * Math.random() - 1);
      porePos[i * 3] = 0.97 * Math.sin(phi) * Math.cos(theta);
      porePos[i * 3 + 1] = 0.97 * Math.sin(phi) * Math.sin(theta);
      porePos[i * 3 + 2] = 0.97 * Math.cos(phi);
    }
    poreGeo.setAttribute("position", new THREE.BufferAttribute(porePos, 3));
    const poreMat = track(new THREE.PointsMaterial({
      color: CELL_COLORS.nuclearPore,
      size: 0.07,
      transparent: true,
      opacity: 0.95,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    }));
    nucleusGroup.add(new THREE.Points(poreGeo, poreMat));

    // Mitochondria — MitoTracker-orange oblong bodies with cristae wireframe overlay
    const mitoMats = [];
    const mitoInnerMats = [];
    const mitoPositions = [[1.25, 0.70, 0.90], [-1.40, 0.35, -0.85], [0.85, -1.30, 0.65], [-0.95, -1.10, 1.10], [1.60, -0.60, -0.40], [-0.50, 1.55, 0.40]];
    mitoPositions.forEach((p, i) => {
      const g = track(new THREE.SphereGeometry(0.28, 20, 18));
      const m = track(new THREE.MeshBasicMaterial({
        color: CELL_COLORS.mitoOuter,
        transparent: true,
        opacity: 0.86
      }));
      mitoMats.push(m);
      const mesh = new THREE.Mesh(g, m);
      mesh.position.set(p[0], p[1], p[2]);
      mesh.scale.set(1.6, 0.7, 0.7);
      mesh.rotation.z = i / mitoPositions.length * Math.PI;
      mesh.rotation.y = i * 0.8;
      cellGroup.add(mesh);
      // cristae — inner wireframe, slightly scaled down
      const iMat = track(new THREE.MeshBasicMaterial({
        color: CELL_COLORS.mitoWire,
        wireframe: true,
        transparent: true,
        opacity: 0.55
      }));
      mitoInnerMats.push(iMat);
      const inner = new THREE.Mesh(g, iMat);
      inner.position.copy(mesh.position);
      inner.scale.copy(mesh.scale).multiplyScalar(0.78);
      inner.rotation.copy(mesh.rotation);
      cellGroup.add(inner);
    });

    // Endoplasmic reticulum — torus-knot + wireframe overlay for reticular detail
    const erGeo = track(new THREE.TorusKnotGeometry(0.75, 0.09, 110, 10, 2, 3));
    const erMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.er,
      transparent: true,
      opacity: 0.55
    }));
    const er = new THREE.Mesh(erGeo, erMat);
    er.position.set(1.15, -0.1, -0.9);
    er.rotation.set(0.6, 0.8, 0);
    cellGroup.add(er);
    const erWireMat = track(new THREE.MeshBasicMaterial({
      color: CELL_COLORS.erWire,
      wireframe: true,
      transparent: true,
      opacity: 0.35
    }));
    const erWire = new THREE.Mesh(erGeo, erWireMat);
    erWire.position.copy(er.position);
    erWire.rotation.copy(er.rotation);
    erWire.scale.setScalar(1.03);
    cellGroup.add(erWire);

    // Golgi apparatus — stacked flat disks (cisternae)
    const golgiMats = [];
    const golgiWireMats = [];
    const golgiGroup = new THREE.Group();
    golgiGroup.position.set(-1.3, 0.85, 0.6);
    golgiGroup.rotation.set(0.4, -0.3, 0.6);
    cellGroup.add(golgiGroup);
    for (let gi = 0; gi < 4; gi++) {
      const r = 0.48 - gi * 0.06;
      const g = track(new THREE.CylinderGeometry(r, r, 0.04, 28, 1, true));
      const m = track(new THREE.MeshBasicMaterial({
        color: CELL_COLORS.golgi,
        transparent: true,
        opacity: 0.55,
        side: THREE.DoubleSide
      }));
      golgiMats.push(m);
      const disk = new THREE.Mesh(g, m);
      disk.position.y = gi * 0.1 - 0.15;
      golgiGroup.add(disk);
      const wm = track(new THREE.MeshBasicMaterial({
        color: CELL_COLORS.golgiWire,
        wireframe: true,
        transparent: true,
        opacity: 0.35
      }));
      golgiWireMats.push(wm);
      const wire = new THREE.Mesh(g, wm);
      wire.position.copy(disk.position);
      wire.scale.setScalar(1.05);
      golgiGroup.add(wire);
    }

    // Transport vesicles — small glowing spheres near the Golgi
    const vesicleN = LOW ? 10 : 22;
    const vesicleGeo = track(new THREE.BufferGeometry());
    const vesiclePos = new Float32Array(vesicleN * 3);
    for (let i = 0; i < vesicleN; i++) {
      // Clustered around Golgi position (-1.3, 0.85, 0.6)
      vesiclePos[i * 3] = -1.3 + (Math.random() - 0.5) * 1.4;
      vesiclePos[i * 3 + 1] = 0.85 + (Math.random() - 0.5) * 1.2;
      vesiclePos[i * 3 + 2] = 0.6 + (Math.random() - 0.5) * 1.2;
    }
    vesicleGeo.setAttribute("position", new THREE.BufferAttribute(vesiclePos, 3));
    const vesicleMat = track(new THREE.PointsMaterial({
      color: CELL_COLORS.vesicles,
      size: 0.08,
      transparent: true,
      opacity: 0.85,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    }));
    cellGroup.add(new THREE.Points(vesicleGeo, vesicleMat));

    // Cytoskeleton — a handful of microtubule-like lines radiating through the cytoplasm
    const cytoskeletonMats = [];
    const microtubuleCount = LOW ? 6 : 12;
    for (let mi = 0; mi < microtubuleCount; mi++) {
      const theta = mi / microtubuleCount * Math.PI * 2 + Math.random() * 0.5;
      const phi = (Math.random() - 0.5) * 0.8;
      const r1 = 1.0,
        r2 = 2.35;
      const a = new THREE.Vector3(r1 * Math.cos(theta) * Math.cos(phi), r1 * Math.sin(phi), r1 * Math.sin(theta) * Math.cos(phi));
      const b = new THREE.Vector3(r2 * Math.cos(theta + 0.3) * Math.cos(phi + 0.2), r2 * Math.sin(phi + 0.2), r2 * Math.sin(theta + 0.3) * Math.cos(phi + 0.2));
      // Curved path with 3 intermediate points
      const curve = new THREE.CatmullRomCurve3([a, a.clone().lerp(b, 0.33).add(new THREE.Vector3(0.1, 0.1, 0.05)), a.clone().lerp(b, 0.66), b]);
      const g = track(new THREE.BufferGeometry().setFromPoints(curve.getPoints(24)));
      const m = track(new THREE.LineBasicMaterial({
        color: CELL_COLORS.cytoskeleton,
        transparent: true,
        opacity: 0.25
      }));
      cytoskeletonMats.push(m);
      cellGroup.add(new THREE.Line(g, m));
    }

    // Ribosomes — vivid magenta dots scattered in cytoplasm (avoid the nucleus region)
    const riboN = LOW ? 60 : 180;
    const riboGeo = track(new THREE.BufferGeometry());
    const riboPos = new Float32Array(riboN * 3);
    let placed = 0;
    while (placed < riboN) {
      const x = (Math.random() - 0.5) * 4.4;
      const y = (Math.random() - 0.5) * 4.4;
      const z = (Math.random() - 0.5) * 4.4;
      const r = Math.sqrt(x * x + y * y + z * z);
      if (r > 1.2 && r < 2.35) {
        riboPos[placed * 3] = x;
        riboPos[placed * 3 + 1] = y;
        riboPos[placed * 3 + 2] = z;
        placed++;
      }
    }
    riboGeo.setAttribute("position", new THREE.BufferAttribute(riboPos, 3));
    const riboMat = track(new THREE.PointsMaterial({
      color: CELL_COLORS.ribosomes,
      size: 0.05,
      transparent: true,
      opacity: 0.9,
      blending: THREE.AdditiveBlending,
      depthWrite: false
    }));
    cellGroup.add(new THREE.Points(riboGeo, riboMat));

    // Lysosomes — small membrane-bound vesicles (digestive enzymes). 3 placed
    // in the cytoplasm; small, high-saturation cyan-purple, with wireframe shell.
    const lysosomeMats = [];
    const lysosomeWireMats = [];
    const lysosomePositions = [[-1.65, 0.10, 0.55], [0.55, 1.55, -0.40], [0.95, -0.45, -1.50]];
    lysosomePositions.forEach(p => {
      const g = track(new THREE.IcosahedronGeometry(0.16, 1));
      const m = track(new THREE.MeshBasicMaterial({
        color: 0xa78bfa,
        transparent: true,
        opacity: 0.85
      }));
      lysosomeMats.push(m);
      const mesh = new THREE.Mesh(g, m);
      mesh.position.set(p[0], p[1], p[2]);
      cellGroup.add(mesh);
      const wm = track(new THREE.LineBasicMaterial({
        color: 0xd0c4ff,
        transparent: true,
        opacity: 0.55
      }));
      lysosomeWireMats.push(wm);
      const wire = new THREE.LineSegments(track(new THREE.EdgesGeometry(g, 1)), wm);
      wire.scale.setScalar(1.15);
      mesh.add(wire);
    });

    // Centrosome — paired centrioles near the nucleus (cell-division organizer).
    // Modelled as two small perpendicular cylinders ("9-triplet barrel" simplified).
    const centrosomeMats = [];
    const centrosomeWireMats = [];
    const centrosomePos = [-1.55, -0.85, -0.20];
    [0, 1].forEach(i => {
      const g = track(new THREE.CylinderGeometry(0.05, 0.05, 0.22, 9, 1, false));
      const m = track(new THREE.MeshBasicMaterial({
        color: 0xffaa66,
        transparent: true,
        opacity: 0.9
      }));
      centrosomeMats.push(m);
      const mesh = new THREE.Mesh(g, m);
      mesh.position.set(centrosomePos[0] + (i ? 0.18 : 0), centrosomePos[1], centrosomePos[2] + (i ? 0 : 0.18));
      mesh.rotation.x = i ? Math.PI / 2 : 0; // orthogonal pair
      cellGroup.add(mesh);
      const wm = track(new THREE.LineBasicMaterial({
        color: 0xffd9a0,
        transparent: true,
        opacity: 0.6
      }));
      centrosomeWireMats.push(wm);
      const wire = new THREE.LineSegments(track(new THREE.EdgesGeometry(g, 1)), wm);
      wire.scale.setScalar(1.06);
      mesh.add(wire);
    });

    // ----------------------------------------------------------------
    // CELL ANCHORS — local-space points each label tracks. We project these
    // through cellGroup.matrixWorld every frame, so as the cell tumbles the
    // labels stay glued to their organelle. Choose anchor points on the
    // *surface* of each organelle so the dot lands on the object, not in it.
    // ----------------------------------------------------------------
    const cellAnchors = [{
      id: "M",
      title: "Plasma Membrane",
      subtitle: "Phospholipid bilayer",
      local: [2.42, 0.55, 0.0]
    }, {
      id: "N",
      title: "Nucleus",
      subtitle: "DNA · 22 chromosomes",
      local: [0.0, 0.95, 0.0]
    }, {
      id: "Nu",
      title: "Nucleolus",
      subtitle: "rRNA synthesis",
      local: [0.20, -0.10, 0.25]
    }, {
      id: "Mi",
      title: "Mitochondrion",
      subtitle: "ATP · cellular power",
      local: [1.40, 0.78, 0.95]
    }, {
      id: "ER",
      title: "Endoplasmic Ret.",
      subtitle: "Protein + lipid synth.",
      local: [1.50, -0.10, -0.95]
    }, {
      id: "G",
      title: "Golgi Apparatus",
      subtitle: "Vesicle packaging",
      local: [-1.50, 0.95, 0.65]
    }, {
      id: "Ly",
      title: "Lysosome",
      subtitle: "Digestive enzymes",
      local: [-1.65, 0.10, 0.55]
    }, {
      id: "C",
      title: "Centrosome",
      subtitle: "Centrioles · MTOC",
      local: [-1.46, -0.85, -0.10]
    }, {
      id: "R",
      title: "Ribosomes",
      subtitle: "Protein synthesis",
      local: [1.70, -1.50, 0.50]
    }];

    // Diagonal rotation axis — gives the cell a tumbling, off-axis spin
    // TWEAK ME — change the components of this axis to alter the tumble direction.
    const CELL_ROT_AXIS = new THREE.Vector3(1, 1.3, 0.5).normalize();
    const CELL_ROT_Q = new THREE.Quaternion();

    // ==========================================================
    //   DNA GROUP
    //   ---------------------------------------------------------
    //   TWEAK ME — DNA color palette. Base colors follow the
    //   standard PyMOL / molecular-viewer convention so the helix
    //   reads as anatomically accurate to anyone with bio training.
    // ==========================================================
    const DNA_COLORS = {
      strand0: 0x5eb5ff,
      // sugar-phosphate backbone, strand 1 — cyan
      strand1: 0xa78bfa,
      // sugar-phosphate backbone, strand 2 — violet
      phosphate: 0xffb84d,
      // phosphate atom beads — warm orange
      phosphateWire: 0xffe0a0,
      // phosphate wireframe edge
      // Standard nucleobase colors (PyMOL convention)
      baseA: 0x66d466,
      // Adenine   — green
      baseT: 0xe06666,
      // Thymine   — red
      baseG: 0x6691ff,
      // Guanine   — blue
      baseC: 0xe8dc66,
      // Cytosine  — yellow
      sugar: 0x67e8c5,
      // Deoxyribose — mint
      rungWire: 0xffffff,
      // wireframe edge over rung bodies
      hbond: 0xb0d0ff // hydrogen bonds — light blue
    };
    const dnaGroup = new THREE.Group();
    scene.add(dnaGroup);

    // Real DNA is ~10.5 base pairs per helical turn. With TURNS=3 that gives ~31 rungs;
    // we use 24 for a slightly cleaner look while still reading as "dense" DNA.
    const DNA_HEIGHT = 4.2,
      TURNS = 3,
      DNA_RADIUS = 0.6,
      SEG = 160;
    const RUNG_COUNT = 24;
    const FOCUS_RUNG_IDX = 12; // middle rung
    const BACKBONE_BEAD_EVERY = 5; // phosphate bead every Nth segment

    const strandPoint = (i, s, p) => {
      const u = i / (SEG - 1);
      const y = (u - 0.5) * DNA_HEIGHT;
      const baseSpin = p * 0.8;
      const angle = u * Math.PI * 2 * TURNS + baseSpin + (s ? Math.PI : 0);
      return [Math.cos(angle) * DNA_RADIUS, y, Math.sin(angle) * DNA_RADIUS];
    };
    const rungEndpoints = (ri, p) => {
      const segI = Math.floor(ri / (RUNG_COUNT - 1) * (SEG - 1));
      return [strandPoint(segI, 0, p), strandPoint(segI, 1, p)];
    };

    // Shared scratch vectors + the cylinder-alignment helper. Defined up here
    // (above the rung setup) so the one-shot setup pass can use alignCylinder.
    const tmp = new THREE.Vector3();
    const tmpUp = new THREE.Vector3(0, 1, 0);
    const tmpA = new THREE.Vector3();
    const tmpB = new THREE.Vector3();
    const alignCylinder = (mesh, a, b, radius = 1) => {
      tmpA.set(a[0], a[1], a[2]);
      tmpB.set(b[0], b[1], b[2]);
      mesh.position.copy(tmpA).add(tmpB).multiplyScalar(0.5);
      const dir = tmp.copy(tmpB).sub(tmpA);
      const len = dir.length();
      dir.normalize();
      mesh.quaternion.setFromUnitVectors(tmpUp, dir);
      mesh.scale.set(radius, len, radius);
    };

    // Helix transforms split into TWO nested groups so we can independently
    // control "self-spin" (around the helix's own axis) and "tilt" (laying it
    // upright vs sideways). All static geometry lives in helixRotationGroup;
    // the tilt group's quaternion changes as the user scrolls into chapter 2.
    const helixTiltGroup = new THREE.Group();
    dnaGroup.add(helixTiltGroup);
    const helixRotationGroup = new THREE.Group();
    helixTiltGroup.add(helixRotationGroup);

    // ----------------------------------------------------------------
    // DNA ANCHORS — local-space points (in helixRotationGroup local coords)
    // that each label sticks to. Projected through helixRotationGroup.matrixWorld
    // every frame so labels track the helix as it tilts and spins.
    // ----------------------------------------------------------------
    const dnaAnchors = [{
      id: "BB",
      title: "Sugar-Phosphate",
      subtitle: "Backbone strand",
      localFn: () => {
        const [x, y, z] = strandPoint(40, 0, 0);
        return [x * 1.45, y, z * 1.45];
      }
    }, {
      id: "BP",
      title: "Base Pair",
      subtitle: "A·T or G·C",
      localFn: () => {
        const [a, b] = rungEndpoints(12, 0);
        return [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2, (a[2] + b[2]) / 2];
      }
    }, {
      id: "MG",
      title: "Major Groove",
      subtitle: "Wide face · 22 Å",
      localFn: () => [DNA_RADIUS * 1.6, 1.05, 0]
    }, {
      id: "mg",
      title: "Minor Groove",
      subtitle: "Narrow face · 12 Å",
      localFn: () => [-DNA_RADIUS * 1.6, -0.5, 0]
    }, {
      id: "5",
      title: "5′ End",
      subtitle: "Phosphate terminus",
      localFn: () => [...strandPoint(SEG - 1, 0, 0)]
    }, {
      id: "3",
      title: "3′ End",
      subtitle: "Hydroxyl terminus",
      localFn: () => [...strandPoint(0, 1, 0)]
    }];

    // --- Strands as thick tubes (no more 1px lines) ---
    // Backbone tube radius is matched to the rung radius so the ladder "frame"
    // reads as one coherent structure.
    const STRAND_RADIUS = 0.05;
    const RUNG_RADIUS = 0.045;
    const strandColors = [DNA_COLORS.strand0, DNA_COLORS.strand1];
    const strandTubes = [];
    [0, 1].forEach(s => {
      const pts = [];
      for (let i = 0; i < SEG; i++) {
        const [x, y, z] = strandPoint(i, s, 0); // build at p=0; group rotation drives animation
        pts.push(new THREE.Vector3(x, y, z));
      }
      const curve = new THREE.CatmullRomCurve3(pts, false, "catmullrom", 0.1);
      const tubeGeo = track(new THREE.TubeGeometry(curve, LOW ? 140 : 260, STRAND_RADIUS, LOW ? 10 : 14, false));
      const tubeMat = track(new THREE.MeshBasicMaterial({
        color: strandColors[s],
        transparent: true,
        opacity: 0.92
      }));
      const tube = new THREE.Mesh(tubeGeo, tubeMat);
      helixRotationGroup.add(tube);
      // Wireframe overlay — low opacity mesh-wireframe (EdgesGeometry on tubes is
      // too sparse to read; full wireframe at low opacity gives a nice "cage").
      const tubeWireMat = track(new THREE.MeshBasicMaterial({
        color: DNA_COLORS.rungWire,
        wireframe: true,
        transparent: true,
        opacity: 0.18
      }));
      const tubeWire = new THREE.Mesh(tubeGeo, tubeWireMat);
      helixRotationGroup.add(tubeWire);
      strandTubes.push({
        tube,
        tubeMat,
        tubeWireMat
      });

      // Phosphate beads — small spheres every Nth segment (ball-and-stick look)
      const beadCount = Math.floor(SEG / BACKBONE_BEAD_EVERY);
      const bpGeo = track(new THREE.BufferGeometry());
      const bpPos = new Float32Array(beadCount * 3);
      for (let bi = 0; bi < beadCount; bi++) {
        const segI = Math.min(SEG - 1, bi * BACKBONE_BEAD_EVERY);
        const [x, y, z] = strandPoint(segI, s, 0);
        bpPos[bi * 3] = x;
        bpPos[bi * 3 + 1] = y;
        bpPos[bi * 3 + 2] = z;
      }
      bpGeo.setAttribute("position", new THREE.BufferAttribute(bpPos, 3));
      const bpMat = track(new THREE.PointsMaterial({
        color: DNA_COLORS.phosphate,
        size: 0.14,
        transparent: true,
        opacity: 0.95,
        blending: THREE.AdditiveBlending,
        depthWrite: false
      }));
      helixRotationGroup.add(new THREE.Points(bpGeo, bpMat));
      strandTubes[s].bpMat = bpMat;
    });

    // --- Background ladder rungs — static, placed once at p=0, rotate with the group ---
    const rungMeshes = [];
    const rungWireMeshes = [];
    const rungMats = [];
    const rungWireMats = [];
    const basePairTypes = ["AT", "TA", "GC", "CG"];
    const rungColorForPair = type => {
      if (type === "AT") return DNA_COLORS.baseA;
      if (type === "TA") return DNA_COLORS.baseT;
      if (type === "GC") return DNA_COLORS.baseG;
      return DNA_COLORS.baseC;
    };
    for (let i = 0; i < RUNG_COUNT; i++) {
      const type = basePairTypes[i % basePairTypes.length];
      const color = rungColorForPair(type);
      const g = track(new THREE.CylinderGeometry(RUNG_RADIUS, RUNG_RADIUS, 1, 12, 1, false));
      const m = track(new THREE.MeshBasicMaterial({
        color,
        transparent: true,
        opacity: 0.85
      }));
      const mesh = new THREE.Mesh(g, m);
      rungMeshes.push(mesh);
      rungMats.push(m);
      helixRotationGroup.add(mesh);
      const edgesGeo = track(new THREE.EdgesGeometry(g, 1));
      const wm = track(new THREE.LineBasicMaterial({
        color: DNA_COLORS.rungWire,
        transparent: true,
        opacity: 0.55
      }));
      const wmesh = new THREE.LineSegments(edgesGeo, wm);
      rungWireMeshes.push(wmesh);
      rungWireMats.push(wm);
      helixRotationGroup.add(wmesh);
      // Place once at p=0 — rotation of the parent group drives the animation.
      const [a, b] = rungEndpoints(i, 0);
      alignCylinder(mesh, a, b, 1);
      alignCylinder(wmesh, a, b, 1.12);
    }

    // --- Sparkly starfield behind everything ---
    // Three layers of twinkling stars at different depths. Each star has its own
    // phase so they twinkle asynchronously. Draws additively for a bright glow.
    const starLayers = [];
    const makeStarLayer = (count, zNear, zFar, size, baseColor) => {
      const pos = new Float32Array(count * 3);
      const col = new Float32Array(count * 3);
      const phase = new Float32Array(count);
      const r = (baseColor >> 16 & 0xff) / 255;
      const g = (baseColor >> 8 & 0xff) / 255;
      const b = (baseColor & 0xff) / 255;
      for (let i = 0; i < count; i++) {
        pos[i * 3] = (Math.random() - 0.5) * 24;
        pos[i * 3 + 1] = (Math.random() - 0.5) * 18;
        pos[i * 3 + 2] = zNear - Math.random() * (zFar - zNear);
        // Slight color variation per star
        const tint = 0.7 + Math.random() * 0.3;
        col[i * 3] = r * tint;
        col[i * 3 + 1] = g * tint;
        col[i * 3 + 2] = b * tint;
        phase[i] = Math.random() * Math.PI * 2;
      }
      const geo = track(new THREE.BufferGeometry());
      geo.setAttribute("position", new THREE.BufferAttribute(pos, 3));
      geo.setAttribute("color", new THREE.BufferAttribute(col, 3));
      const mat = track(new THREE.PointsMaterial({
        vertexColors: true,
        size,
        transparent: true,
        opacity: 0.9,
        blending: THREE.AdditiveBlending,
        depthWrite: false
      }));
      const points = new THREE.Points(geo, mat);
      scene.add(points);
      starLayers.push({
        points,
        geo,
        mat,
        count,
        phase,
        col
      });
    };
    // Far layer (dim, many, bluish)
    makeStarLayer(LOW ? 200 : 500, -14, -24, 0.025, 0x8090c8);
    // Mid layer (medium, pinkish)
    makeStarLayer(LOW ? 80 : 200, -6, -14, 0.04, 0xb890e0);
    // Near sparkle layer (few, bright white)
    makeStarLayer(LOW ? 30 : 80, -2, -8, 0.065, 0xffffff);

    // ==========================================================
    //   ANIMATION LOOP
    // ==========================================================
    const cellWorldPos = new THREE.Vector3();
    const nucleusWorldPos = new THREE.Vector3();

    // --- Visibility: pause rendering when the pinned section is off-screen ---
    let visible = true;
    const vio = new IntersectionObserver(([e]) => {
      visible = e.isIntersecting;
    }, {
      threshold: 0
    });
    vio.observe(mount);
    let raf,
      last = performance.now();
    const loop = t => {
      const dt = Math.min(0.05, (t - last) / 1000);
      last = t;

      // Skip render + heavy per-frame updates when section is scrolled out of view.
      if (!visible) {
        raf = requestAnimationFrame(loop);
        return;
      }
      const p = pRef.current; // 0..4  (4 chapters: cell → helix → pair → reassemble)

      // ============================================================
      //  PHASE VISIBILITY
      // ============================================================
      const cellFade = 1 - ss(0.7, 1.4, p); // cell fades out entering helix
      const dnaFade = ss(0.7, 1.5, p); // helix fades in

      // Tumbling diagonal rotation — quaternion around an off-axis vector
      CELL_ROT_Q.setFromAxisAngle(CELL_ROT_AXIS, dt * 0.18);
      cellGroup.quaternion.multiply(CELL_ROT_Q);
      // Slight pulsing of nucleus draws the eye before zoom-in
      const nucPulse = 1 + 0.04 * Math.sin(t * 0.002);
      nucleusGroup.scale.setScalar(nucPulse);

      // Apply cell fade per-material (all tracked here so fade-out stays uniform)
      setOpacity(cytoMat, 0.14 * cellFade);
      setOpacity(cytoWireMat, 0.09 * cellFade);
      setOpacity(memMat, 0.10 * cellFade);
      setOpacity(memWireMat, 0.22 * cellFade);
      setOpacity(bilayerMat, 0.75 * cellFade);
      setOpacity(nucMat, 0.55 * cellFade);
      setOpacity(nucWireMat, 0.40 * cellFade);
      setOpacity(nucleolusMat, 0.85 * cellFade);
      setOpacity(nucleolusWireMat, 0.50 * cellFade);
      setOpacity(poreMat, 0.95 * cellFade);
      setOpacity(erMat, 0.55 * cellFade);
      setOpacity(erWireMat, 0.35 * cellFade);
      setOpacity(riboMat, 0.90 * cellFade);
      setOpacity(vesicleMat, 0.85 * cellFade);
      mitoMats.forEach(m => setOpacity(m, 0.86 * cellFade));
      mitoInnerMats.forEach(m => setOpacity(m, 0.55 * cellFade));
      golgiMats.forEach(m => setOpacity(m, 0.55 * cellFade));
      golgiWireMats.forEach(m => setOpacity(m, 0.35 * cellFade));
      chromatinMats.forEach(m => setOpacity(m, 0.50 * cellFade));
      cytoskeletonMats.forEach(m => setOpacity(m, 0.25 * cellFade));

      // ============================================================
      //  DNA — drive the whole helix by rotating its group.
      //  Strands + rungs are static geometry built at p=0; rotating the group
      //  is equivalent to the old per-frame position updates but far cheaper.
      // ============================================================
      helixRotationGroup.rotation.y = p * 0.8;

      // Strand tube + wireframe + bead opacities (shared dnaFade)
      for (const S of strandTubes) {
        setOpacity(S.tubeMat, 0.92 * dnaFade);
        setOpacity(S.tubeWireMat, 0.18 * dnaFade);
        setOpacity(S.bpMat, 0.95 * dnaFade);
      }

      // Rung opacities — uniform fade with the rest of the helix.
      for (let i = 0; i < RUNG_COUNT; i++) {
        setOpacity(rungMats[i], 0.85 * dnaFade);
        setOpacity(rungWireMats[i], 0.55 * dnaFade);
      }

      // ============================================================
      //  HELIX TILT — upright (chapter 1) → sideways (chapter 2 end)
      //  We rotate the parent helixTiltGroup around the Z axis so the
      //  helix's Y-axis (its long axis) sweeps from vertical to horizontal.
      //  Self-spin still happens on helixRotationGroup independently.
      // ============================================================
      const tiltAmt = ss(2.0, 2.7, p); // 0..1 over chapter 2
      const tiltAngle = -Math.PI * 0.5 * tiltAmt; // 0 → -90°
      helixTiltGroup.rotation.z = tiltAngle;
      // Slight x-tilt during the lay-down so the viewer sees a 3/4 view, not pure side
      helixTiltGroup.rotation.x = 0.18 * tiltAmt;

      // ============================================================
      //  CAMERA PATH — three chapters, mostly held positions.
      //  · 0..1 cell overview → close
      //  · 1..2 zoom toward nucleus, helix reveal
      //  · 2..3 pull back slightly so the laid-down helix fits the frame
      // ============================================================
      cellGroup.getWorldPosition(cellWorldPos);
      nucleusGroup.getWorldPosition(nucleusWorldPos);
      const camPos = new THREE.Vector3();
      const lookAt = new THREE.Vector3();
      const WP = {
        cellOverview: new THREE.Vector3(0, 0.2, 9),
        cellClose: new THREE.Vector3(0, 0.0, 4.0),
        helixEst: new THREE.Vector3(0.0, 0.0, 5.5),
        helixOut: new THREE.Vector3(0.0, 0.2, 6.8)
      };
      if (p < 1) {
        const k = ss(0, 1, p);
        camPos.copy(WP.cellOverview).lerp(WP.cellClose, k);
        lookAt.set(0, 0, 0);
      } else if (p < 2) {
        // Reach helix-establish view by ~70% of the chapter, then hold.
        const k = ss(1.0, 1.7, p);
        camPos.copy(WP.cellClose).lerp(WP.helixEst, k);
        lookAt.set(0, 0, 0);
      } else {
        // Pull back gently so the laid-down (horizontal) helix still fits.
        const k = ss(2.0, 2.7, p);
        camPos.copy(WP.helixEst).lerp(WP.helixOut, k);
        lookAt.set(0, 0, 0);
      }
      camera.position.copy(camPos);
      camera.lookAt(lookAt);

      // ============================================================
      //  LABEL OVERLAY — anchor-driven projection.
      //  Each anchor stores a LOCAL-SPACE point on its group (cell or helix);
      //  every frame we transform through the group's matrixWorld and project
      //  to NDC. The dot lands on the actual organelle / structure.
      // ============================================================
      const labels = [];
      const project = v => {
        tmp.copy(v).project(camera);
        if (tmp.z > 1) return null;
        return {
          x: (tmp.x * 0.5 + 0.5) * 100,
          y: (-tmp.y * 0.5 + 0.5) * 100
        };
      };
      const projectLocal = (group, local) => {
        const v = new THREE.Vector3(local[0], local[1], local[2]).applyMatrix4(group.matrixWorld);
        return project(v);
      };

      // CELL labels — long-lasting (in: 0.15, out: 1.55) so the reader has
      // time to read each organelle's callout. Anchors are surface points.
      const cellLabelFade = ss(0.15, 0.55, p) * (1 - ss(1.25, 1.55, p));
      if (cellLabelFade > 0.02) {
        for (const a of cellAnchors) {
          const pos = projectLocal(cellGroup, a.local);
          if (pos) labels.push({
            id: a.id,
            title: a.title,
            subtitle: a.subtitle,
            x: pos.x,
            y: pos.y,
            fade: cellLabelFade
          });
        }
      }

      // DNA labels — appear once the helix is established, last through the
      // tilt animation, and out as the chapter ends. Each anchor uses a
      // function so it can sample current strand/rung positions.
      const dnaLabelFade = ss(1.5, 1.9, p) * (1 - ss(2.85, 3.0, p));
      if (dnaLabelFade > 0.02) {
        for (const a of dnaAnchors) {
          const local = a.localFn();
          const pos = projectLocal(helixRotationGroup, local);
          if (pos) labels.push({
            id: a.id,
            title: a.title,
            subtitle: a.subtitle,
            x: pos.x,
            y: pos.y,
            fade: dnaLabelFade
          });
        }
      }
      window.dispatchEvent(new CustomEvent("pin-labels-update", {
        detail: labels
      }));

      // Twinkle star layers — per-layer opacity breathing. Per-star color jitter
      // via the `color` attribute would also work but costs a buffer upload every
      // frame; opacity-modulated additive points read as twinkling well enough.
      const tsec = t * 0.001;
      for (let li = 0; li < starLayers.length; li++) {
        const L = starLayers[li];
        // Each layer breathes at slightly different rates/phases for variety
        const k = 0.75 + 0.25 * Math.sin(tsec * (0.6 + li * 0.25) + li * 1.3);
        L.mat.opacity = (li === starLayers.length - 1 ? 0.9 : 0.65) * k;
      }
      renderer.render(scene, camera);
      raf = requestAnimationFrame(loop);
    };
    if (REDUCED) {
      // Render a single static frame and stop the loop; scroll still works but nothing animates.
      renderer.render(scene, camera);
    } else {
      raf = requestAnimationFrame(loop);
    }
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      vio.disconnect();
      renderer.dispose();
      disposables.forEach(d => {
        try {
          d.dispose && d.dispose();
        } catch (e) {}
      });
      if (renderer.domElement.parentNode === mount) mount.removeChild(renderer.domElement);
    };
  }, []);
  return /*#__PURE__*/React.createElement("div", {
    ref: mountRef,
    style: {
      position: "absolute",
      inset: 0
    }
  });
};

// ---------- LABEL OVERLAY ----------
const PinLabels = () => {
  const [labels, setLabels] = React.useState([]);
  React.useEffect(() => {
    const onUpdate = e => setLabels(e.detail);
    window.addEventListener("pin-labels-update", onUpdate);
    return () => window.removeEventListener("pin-labels-update", onUpdate);
  }, []);
  return /*#__PURE__*/React.createElement("div", {
    className: "pin-labels"
  }, labels.map(L => /*#__PURE__*/React.createElement("div", {
    key: L.id,
    className: "pin-label",
    style: {
      left: `${L.x}%`,
      top: `${L.y}%`,
      opacity: L.fade
    }
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-label-dot"
  }), /*#__PURE__*/React.createElement("div", {
    className: "pin-label-line"
  }), /*#__PURE__*/React.createElement("div", {
    className: "pin-label-box"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-label-id"
  }, L.id), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    className: "pin-label-title"
  }, L.title), /*#__PURE__*/React.createElement("div", {
    className: "pin-label-sub"
  }, L.subtitle))))));
};
window.PinScene = PinScene;
window.PinLabels = PinLabels;
