// AUTO-GENERATED by compile.cjs from sections.jsx — do not edit by hand.
/* global React */
// All page sections. Data is read from window.PROJECTS, window.EXPERIENCE, window.SKILLS
// which are defined in js/data.js — edit that file to add entries.

// ---------- ABOUT ----------
window.About = () => /*#__PURE__*/React.createElement("section", {
  className: "about",
  id: "about",
  "data-screen-label": "about"
}, /*#__PURE__*/React.createElement("div", {
  className: "about-portrait"
}, /*#__PURE__*/React.createElement("div", {
  className: "about-portrait-frame"
}, /*#__PURE__*/React.createElement("img", {
  src: "assets/Headshot.jpeg",
  alt: "Brenen Olson"
})), /*#__PURE__*/React.createElement("div", {
  className: "about-portrait-meta"
}, /*#__PURE__*/React.createElement("div", null, "Location", /*#__PURE__*/React.createElement("span", null, "Minneapolis, MN")), /*#__PURE__*/React.createElement("div", null, "Degree", /*#__PURE__*/React.createElement("span", null, "B.S. Computer Science")), /*#__PURE__*/React.createElement("div", null, "GPA", /*#__PURE__*/React.createElement("span", null, "3.809 / 4.000")), /*#__PURE__*/React.createElement("div", null, "Dean's List", /*#__PURE__*/React.createElement("span", null, "5\xD7 semesters")))), /*#__PURE__*/React.createElement("div", {
  className: "about-body"
}, /*#__PURE__*/React.createElement("div", {
  className: "section-label"
}, /*#__PURE__*/React.createElement("span", {
  className: "section-num"
}, "01"), " about"), /*#__PURE__*/React.createElement("p", {
  className: "about-statement"
}, "I'm a ", /*#__PURE__*/React.createElement("em", null, "graphics engineer"), " and ", /*#__PURE__*/React.createElement("em", null, "full-stack developer"), " with a B.S. in Computer Science from UMN. I write ", /*#__PURE__*/React.createElement("em", {
  className: "med"
}, "real-time shaders"), ", build physics simulators, and ship production software \u2014 the whole pipeline from GPU to product, built by one person."), /*#__PURE__*/React.createElement("div", {
  className: "about-cards"
}, /*#__PURE__*/React.createElement("div", {
  className: "about-card"
}, /*#__PURE__*/React.createElement("div", {
  className: "about-card-k"
}, "Core"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-v"
}, "Real-time graphics"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-note"
}, "GLSL, Unreal 5, Three.js, rigid-body physics.")), /*#__PURE__*/React.createElement("div", {
  className: "about-card"
}, /*#__PURE__*/React.createElement("div", {
  className: "about-card-k"
}, "Also"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-v"
}, "Full-stack product"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-note"
}, "Vue 3, Blazor, Supabase, Cloudflare \u2014 shipped.")), /*#__PURE__*/React.createElement("div", {
  className: "about-card"
}, /*#__PURE__*/React.createElement("div", {
  className: "about-card-k"
}, "Research"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-v"
}, "6-DoF simulation"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-note"
}, "Cable-driven spacecraft motion sim w/ Cornell.")), /*#__PURE__*/React.createElement("div", {
  className: "about-card"
}, /*#__PURE__*/React.createElement("div", {
  className: "about-card-k"
}, "Approach"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-v"
}, "End-to-end"), /*#__PURE__*/React.createElement("div", {
  className: "about-card-note"
}, "Shader to UI, firmware to cloud \u2014 no handoffs.")))));

// ---------- PINNED SCROLL ----------
window.PinSection = () => {
  const wrapRef = React.useRef(null);
  const [progress, setProgress] = React.useState(0); // 0..4
  const [chapter, setChapter] = React.useState(0);
  React.useEffect(() => {
    const onScroll = () => {
      if (!wrapRef.current) return;
      const rect = wrapRef.current.getBoundingClientRect();
      const total = wrapRef.current.offsetHeight - window.innerHeight;
      const scrolled = Math.min(Math.max(-rect.top, 0), total);
      const p = scrolled / total * 4; // four chapters → 0..4
      setProgress(p);
      setChapter(Math.min(3, Math.max(0, Math.round(p))));
    };
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    onScroll();
    return () => window.removeEventListener("scroll", onScroll);
  }, []);
  const chapters = [{
    title: "Approach",
    headline: "Two meters. Six micrometers.",
    sub: "Every cell in your body holds two meters of DNA, coiled into a nucleus smaller than a grain of sand. What you're approaching is a single fragment — less than a millionth of the full strand."
  }, {
    title: "Backbone",
    headline: "The outer rails.",
    sub: "Two sugar-phosphate spines, linked by phosphodiester bonds, form the outer rails of the ladder. The sequence of bases — A, T, G, C — hangs inward, readable only through the major groove."
  }, {
    title: "Helix",
    headline: "Right-handed. Antiparallel.",
    sub: "10.4 base pairs per full twist. One strand runs 5′ to 3′; the other runs 3′ to 5′ in the opposite direction. The twist carves two grooves — major and minor — that proteins land on to read or regulate the code."
  }, {
    title: "Structure",
    headline: "Four letters. Infinite sequences.",
    sub: "A pairs with T by two hydrogen bonds; G pairs with C by three. The extra bond in G·C makes those pairs more thermally stable — a fact evolution has written into every promoter, every regulatory switch."
  }];
  return /*#__PURE__*/React.createElement("section", {
    className: "pin-wrap",
    ref: wrapRef,
    id: "pin",
    "data-screen-label": "pinned-scroll"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-sticky"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-3d"
  }, /*#__PURE__*/React.createElement(window.PinScene, {
    progress: progress
  }), /*#__PURE__*/React.createElement(window.PinLabels, null)), /*#__PURE__*/React.createElement("div", {
    className: "pin-overlay"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-header"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-title-block"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-counter"
  }, /*#__PURE__*/React.createElement("span", {
    className: "idx"
  }, "0", chapter + 1), "/04 \xB7 graphics demo \xB7 scroll-driven"), /*#__PURE__*/React.createElement("h2", {
    className: "pin-headline"
  }, chapters[chapter].headline), /*#__PURE__*/React.createElement("p", {
    className: "pin-sub"
  }, chapters[chapter].sub)), /*#__PURE__*/React.createElement("div", {
    className: "pin-chapter-rail"
  }, chapters.map((c, i) => /*#__PURE__*/React.createElement("div", {
    key: c.title,
    className: `pin-chapter ${i === chapter ? "active" : ""}`
  }, /*#__PURE__*/React.createElement("span", {
    className: "pin-chapter-line"
  }), c.title)))), /*#__PURE__*/React.createElement("div", {
    className: "pin-footer"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-tag"
  }, "approach \u2192 backbone \u2192 helix \u2192 structure"), /*#__PURE__*/React.createElement("div", {
    className: "pin-progress-bar",
    style: {
      "--p": `${progress / 4 * 100}%`
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "pin-tag"
  }, Math.round(progress / 4 * 100), "%")))));
};

// ---------- PROJECTS ----------
window.Projects = () => {
  const [view, setView] = React.useState("featured"); // "featured" | "all" | "graphics" | "live"
  const [openId, setOpenId] = React.useState(null);
  const PROJECTS = window.PROJECTS || [];
  const shown = view === "featured" ? PROJECTS.filter(p => p.highlight) : PROJECTS.filter(p => {
    if (view === "all") return true;
    if (view === "graphics") return p.category === "graphics";
    if (view === "live") return p.status === "live";
    return true;
  });
  const featured = shown.filter(p => p.featured);
  const rest = shown.filter(p => !p.featured);
  const openProject = PROJECTS.find(p => p.id === openId);
  React.useEffect(() => {
    if (!openId) return;
    const onKey = e => {
      if (e.key === "Escape") setOpenId(null);
    };
    window.addEventListener("keydown", onKey);
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = "";
    };
  }, [openId]);
  return /*#__PURE__*/React.createElement("section", {
    className: "projects",
    id: "projects",
    "data-screen-label": "projects"
  }, /*#__PURE__*/React.createElement("div", {
    className: "projects-head"
  }, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
    className: "section-label"
  }, /*#__PURE__*/React.createElement("span", {
    className: "section-num"
  }, "03"), " selected work"), /*#__PURE__*/React.createElement("h2", {
    className: "section-head"
  }, "Projects shipped,", /*#__PURE__*/React.createElement("br", null), "simulated, and built."), /*#__PURE__*/React.createElement("p", {
    className: "section-sub"
  }, "Shipped products, graphics work, and personal builds. Click any card for the details.")), /*#__PURE__*/React.createElement("div", {
    className: "projects-filter"
  }, [["featured", "featured"], ["graphics", "graphics"], ["live", "shipped"], ["all", "all"]].map(([k, label]) => /*#__PURE__*/React.createElement("button", {
    key: k,
    className: `filter-btn ${view === k ? "active" : ""}`,
    onClick: () => setView(k)
  }, label)))), featured.length > 0 && /*#__PURE__*/React.createElement("div", {
    className: "featured"
  }, featured.slice(0, 2).map((p, i) => /*#__PURE__*/React.createElement(ProjectCard, {
    key: p.id,
    p: p,
    tall: i === 0 && featured.length > 1,
    onOpen: setOpenId
  }))), /*#__PURE__*/React.createElement("div", {
    className: "project-grid"
  }, [...featured.slice(2), ...rest].map(p => /*#__PURE__*/React.createElement(ProjectCard, {
    key: p.id,
    p: p,
    onOpen: setOpenId
  }))), view === "featured" && /*#__PURE__*/React.createElement("div", {
    className: "projects-browse-row"
  }, /*#__PURE__*/React.createElement("button", {
    className: "projects-view-all-btn",
    onClick: () => setView("all")
  }, "view all projects \u2192")), openProject && /*#__PURE__*/React.createElement(ProjectModal, {
    p: openProject,
    onClose: () => setOpenId(null)
  }));
};
const ProjectCard = ({
  p,
  tall,
  onOpen
}) => /*#__PURE__*/React.createElement("div", {
  className: `project-card ${tall ? "tall" : ""}`,
  onClick: () => onOpen(p.id)
}, /*#__PURE__*/React.createElement("div", {
  className: "project-media"
}, p.img ? /*#__PURE__*/React.createElement("img", {
  src: p.img,
  alt: p.title
}) : /*#__PURE__*/React.createElement(PlaceholderGraphic, {
  id: p.id
}), p.badge && /*#__PURE__*/React.createElement("div", {
  className: "project-badge"
}, p.badge), p.status === "live" && /*#__PURE__*/React.createElement("div", {
  className: "project-shipping live"
}, "Live"), /*#__PURE__*/React.createElement("div", {
  className: "project-open-hint"
}, "view case study ", /*#__PURE__*/React.createElement("span", null, "\u2192"))), /*#__PURE__*/React.createElement("div", {
  className: "project-body"
}, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
  className: "project-tag"
}, p.tag), /*#__PURE__*/React.createElement("h3", {
  className: "project-title"
}, p.title), p.subtitle && /*#__PURE__*/React.createElement("div", {
  className: "project-subtitle"
}, p.subtitle)), /*#__PURE__*/React.createElement("p", {
  className: "project-desc"
}, p.desc), /*#__PURE__*/React.createElement("div", {
  className: "project-stack-row"
}, p.stack.flatMap(g => g.items).slice(0, 5).map((s, i) => /*#__PURE__*/React.createElement("span", {
  key: s + i,
  className: "project-chip"
}, s)), p.stack.flatMap(g => g.items).length > 5 && /*#__PURE__*/React.createElement("span", {
  className: "project-chip more"
}, "+", p.stack.flatMap(g => g.items).length - 5)), p.links && p.links.length > 0 && /*#__PURE__*/React.createElement("div", {
  className: "project-card-links",
  onClick: e => e.stopPropagation()
}, p.links.map(l => /*#__PURE__*/React.createElement("a", {
  key: l.label,
  href: l.href,
  target: "_blank",
  rel: "noreferrer",
  className: "project-card-link"
}, l.label === "github" ? "↗ github" : `↗ ${l.label}`)))));
const ProjectModal = ({
  p,
  onClose
}) => /*#__PURE__*/React.createElement("div", {
  className: "pm-overlay",
  onClick: e => {
    if (e.target === e.currentTarget) onClose();
  }
}, /*#__PURE__*/React.createElement("div", {
  className: "pm-dialog"
}, /*#__PURE__*/React.createElement("div", {
  className: "pm-hero"
}, p.hero ? /*#__PURE__*/React.createElement("img", {
  src: p.hero,
  alt: p.title
}) : /*#__PURE__*/React.createElement(PlaceholderGraphic, {
  id: p.id
}), /*#__PURE__*/React.createElement("div", {
  className: "pm-hero-scrim"
}), /*#__PURE__*/React.createElement("div", {
  className: "pm-hero-badge"
}, p.tag), /*#__PURE__*/React.createElement("button", {
  className: "pm-close",
  onClick: onClose,
  "aria-label": "close"
}, /*#__PURE__*/React.createElement("svg", {
  width: "14",
  height: "14",
  viewBox: "0 0 14 14"
}, /*#__PURE__*/React.createElement("path", {
  d: "M2 2l10 10M12 2L2 12",
  stroke: "currentColor",
  strokeWidth: "1.5",
  strokeLinecap: "round"
})))), /*#__PURE__*/React.createElement("div", {
  className: "pm-body"
}, /*#__PURE__*/React.createElement("div", {
  className: "pm-header"
}, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("h3", {
  className: "pm-title"
}, p.title), p.subtitle && /*#__PURE__*/React.createElement("div", {
  className: "pm-subtitle"
}, p.subtitle)), p.status === "live" && /*#__PURE__*/React.createElement("div", {
  className: "pm-status live"
}, /*#__PURE__*/React.createElement("span", null), "Live in production")), /*#__PURE__*/React.createElement("div", {
  className: "pm-meta"
}, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
  className: "pm-meta-k"
}, "Year"), /*#__PURE__*/React.createElement("div", {
  className: "pm-meta-v"
}, p.year)), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
  className: "pm-meta-k"
}, "Role"), /*#__PURE__*/React.createElement("div", {
  className: "pm-meta-v"
}, p.role)), /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
  className: "pm-meta-k"
}, "Scale"), /*#__PURE__*/React.createElement("div", {
  className: "pm-meta-v"
}, p.scale))), /*#__PURE__*/React.createElement("p", {
  className: "pm-desc"
}, p.desc), /*#__PURE__*/React.createElement("div", {
  className: "pm-section-title"
}, "// what I built"), /*#__PURE__*/React.createElement("ul", {
  className: "pm-bullets"
}, p.long.map((l, i) => /*#__PURE__*/React.createElement("li", {
  key: i
}, l))), /*#__PURE__*/React.createElement("div", {
  className: "pm-section-title"
}, "// stack"), /*#__PURE__*/React.createElement("div", {
  className: "pm-stack-grid"
}, p.stack.map(g => /*#__PURE__*/React.createElement("div", {
  key: g.cat,
  className: "pm-stack-col"
}, /*#__PURE__*/React.createElement("div", {
  className: "pm-stack-cat"
}, g.cat), /*#__PURE__*/React.createElement("div", {
  className: "pm-stack-items"
}, g.items.map(s => /*#__PURE__*/React.createElement("span", {
  key: s,
  className: "pm-chip"
}, s)))))), p.links && p.links.length > 0 && /*#__PURE__*/React.createElement("div", {
  className: "pm-links"
}, p.links.map(l => /*#__PURE__*/React.createElement("a", {
  key: l.label,
  href: l.href,
  target: "_blank",
  rel: "noreferrer",
  className: "pm-link"
}, l.label, " ", /*#__PURE__*/React.createElement("span", null, "\u2197")))))));
const PlaceholderGraphic = ({
  id
}) => {
  const hue = id.charCodeAt(0) * 17 % 360;
  return /*#__PURE__*/React.createElement("svg", {
    width: "100%",
    height: "100%",
    viewBox: "0 0 400 250",
    style: {
      position: "absolute",
      inset: 0
    }
  }, /*#__PURE__*/React.createElement("defs", null, /*#__PURE__*/React.createElement("linearGradient", {
    id: `g-${id}`,
    x1: "0",
    y1: "0",
    x2: "1",
    y2: "1"
  }, /*#__PURE__*/React.createElement("stop", {
    offset: "0",
    stopColor: `hsl(${hue}, 70%, 30%)`
  }), /*#__PURE__*/React.createElement("stop", {
    offset: "1",
    stopColor: `hsl(${(hue + 60) % 360}, 70%, 20%)`
  })), /*#__PURE__*/React.createElement("pattern", {
    id: `s-${id}`,
    width: "20",
    height: "20",
    patternUnits: "userSpaceOnUse"
  }, /*#__PURE__*/React.createElement("path", {
    d: "M0 20L20 0",
    stroke: `hsl(${hue}, 80%, 60%)`,
    strokeWidth: "0.5",
    opacity: "0.3"
  }))), /*#__PURE__*/React.createElement("rect", {
    width: "400",
    height: "250",
    fill: `url(#g-${id})`
  }), /*#__PURE__*/React.createElement("rect", {
    width: "400",
    height: "250",
    fill: `url(#s-${id})`
  }), /*#__PURE__*/React.createElement("text", {
    x: "20",
    y: "235",
    fontFamily: "JetBrains Mono",
    fontSize: "10",
    fill: "rgba(255,255,255,0.4)",
    letterSpacing: "2"
  }, id.toUpperCase(), ".PREVIEW"));
};

// ---------- INTERACTIVE GRAPHICS DEMO — BOIDS FLOCKING ----------
// A real-time Reynolds flocking simulation (1987), running in your browser.
// Each boid obeys three steering rules: separation (avoid crowding), alignment
// (match neighbor heading), cohesion (move toward neighbor centroid). Cursor
// acts as a predator — boids flee from it. Click to scatter the flock.
//
// This is the "skills demo": a classical graphics algorithm built from scratch,
// rendered with Canvas2D + additive-style glow + velocity-based color ramps.
window.BoidsGame = () => {
  const canvasRef = React.useRef(null);
  const [scatters, setScatters] = React.useState(0);
  const [population, setPopulation] = React.useState(0);
  React.useEffect(() => {
    const c = canvasRef.current;
    if (!c) return;
    const ctx = c.getContext("2d");
    const LOW = typeof window !== "undefined" && window.__QUALITY__ === "low";
    const dpr = () => Math.min(window.devicePixelRatio || 1, 2);
    const resize = () => {
      c.width = c.clientWidth * dpr();
      c.height = c.clientHeight * dpr();
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.scale(dpr(), dpr());
    };
    resize();
    const ro = new ResizeObserver(resize);
    ro.observe(c);
    const W = () => c.clientWidth,
      H = () => c.clientHeight;

    // --- Boid population ---
    const BOID_COUNT = LOW ? 90 : 180;
    setPopulation(BOID_COUNT);
    const boids = [];
    for (let i = 0; i < BOID_COUNT; i++) {
      boids.push({
        x: Math.random() * W(),
        y: Math.random() * H(),
        vx: (Math.random() - 0.5) * 2,
        vy: (Math.random() - 0.5) * 2,
        hue: Math.random() // 0..1 → cyan→magenta color ramp
      });
    }

    // --- Interaction state ---
    const mouse = {
      x: -1e6,
      y: -1e6
    };
    const onMove = e => {
      const rect = c.getBoundingClientRect();
      mouse.x = e.clientX - rect.left;
      mouse.y = e.clientY - rect.top;
    };
    const onLeave = () => {
      mouse.x = mouse.y = -1e6;
    };
    const onClick = e => {
      const rect = c.getBoundingClientRect();
      const cx = e.clientX - rect.left,
        cy = e.clientY - rect.top;
      // Shockwave scatter — radial push from click point
      for (const b of boids) {
        const dx = b.x - cx,
          dy = b.y - cy;
        const d = Math.hypot(dx, dy);
        if (d < 320) {
          const force = (1 - d / 320) * 14;
          b.vx += dx / (d || 1) * force;
          b.vy += dy / (d || 1) * force;
        }
      }
      setScatters(s => s + 1);
    };
    c.addEventListener("mousemove", onMove);
    c.addEventListener("mouseleave", onLeave);
    c.addEventListener("click", onClick);

    // --- Tunables (TWEAK ME if you want different flocking behavior) ---
    const VIEW_R = 50; // radius within which neighbors count
    const SEP_R = 20; // personal space
    const MAX_V = 3.2; // speed cap
    const FLEE_R = 90; // cursor-avoidance radius
    const ALIGN_W = 0.06; // alignment weight
    const COHESION_W = 0.003;
    const SEP_W = 0.15;
    const FLEE_W = 5; // strength when fleeing predator (cursor)

    let raf;
    const loop = () => {
      const w = W(),
        h = H();

      // --- Trail-friendly fade (alpha-dim instead of clear) ---
      ctx.fillStyle = "rgba(5, 6, 10, 0.22)";
      ctx.fillRect(0, 0, w, h);

      // --- Flocking update (O(N²); fine at 180) ---
      for (let i = 0; i < boids.length; i++) {
        const b = boids[i];
        let ax = 0,
          ay = 0; // accumulated neighbor velocity
        let cxs = 0,
          cys = 0; // accumulated neighbor position
        let sepX = 0,
          sepY = 0; // separation accumulator
        let nCount = 0,
          sCount = 0;
        for (let j = 0; j < boids.length; j++) {
          if (j === i) continue;
          const o = boids[j];
          const dx = o.x - b.x,
            dy = o.y - b.y;
          const d2 = dx * dx + dy * dy;
          if (d2 < VIEW_R * VIEW_R) {
            ax += o.vx;
            ay += o.vy;
            cxs += o.x;
            cys += o.y;
            nCount++;
            if (d2 < SEP_R * SEP_R) {
              const d = Math.sqrt(d2) || 1;
              sepX -= dx / d;
              sepY -= dy / d;
              sCount++;
            }
          }
        }
        if (nCount > 0) {
          ax /= nCount;
          ay /= nCount;
          cxs /= nCount;
          cys /= nCount;
          // Alignment
          b.vx += (ax - b.vx) * ALIGN_W;
          b.vy += (ay - b.vy) * ALIGN_W;
          // Cohesion
          b.vx += (cxs - b.x) * COHESION_W;
          b.vy += (cys - b.y) * COHESION_W;
        }
        if (sCount > 0) {
          b.vx += sepX * SEP_W;
          b.vy += sepY * SEP_W;
        }

        // Flee the cursor (predator)
        const mdx = b.x - mouse.x,
          mdy = b.y - mouse.y;
        const md = Math.hypot(mdx, mdy);
        if (md < FLEE_R) {
          const force = (1 - md / FLEE_R) * FLEE_W;
          b.vx += mdx / (md || 1) * force;
          b.vy += mdy / (md || 1) * force;
        }

        // Cap speed
        const v = Math.hypot(b.vx, b.vy);
        if (v > MAX_V) {
          b.vx = b.vx / v * MAX_V;
          b.vy = b.vy / v * MAX_V;
        }

        // Integrate
        b.x += b.vx;
        b.y += b.vy;

        // Wrap edges
        if (b.x < -10) b.x = w + 10;else if (b.x > w + 10) b.x = -10;
        if (b.y < -10) b.y = h + 10;else if (b.y > h + 10) b.y = -10;
      }

      // --- Draw each boid as an oriented triangle with velocity-tinted glow ---
      for (const b of boids) {
        const angle = Math.atan2(b.vy, b.vx);
        const speed = Math.hypot(b.vx, b.vy);
        const speedN = Math.min(1, speed / MAX_V);
        // Color ramp: cyan (#5eb5ff) → magenta (#e879f9) driven by hue + speed
        const t = (b.hue + speedN * 0.5) % 1;
        const r = Math.round(94 + (232 - 94) * t);
        const g = Math.round(181 + (121 - 181) * t);
        const bC = Math.round(255 - 6 * t);
        const size = 4 + speedN * 3;
        ctx.save();
        ctx.translate(b.x, b.y);
        ctx.rotate(angle);
        ctx.shadowColor = `rgb(${r},${g},${bC})`;
        ctx.shadowBlur = 6 + speedN * 8;
        ctx.fillStyle = `rgba(${r},${g},${bC},0.95)`;
        ctx.beginPath();
        ctx.moveTo(size * 1.4, 0);
        ctx.lineTo(-size * 0.9, size * 0.7);
        ctx.lineTo(-size * 0.9, -size * 0.7);
        ctx.closePath();
        ctx.fill();
        ctx.restore();
      }
      ctx.shadowBlur = 0;

      // --- Subtle cursor indicator (predator) ---
      if (mouse.x > -1000) {
        ctx.strokeStyle = "rgba(232, 121, 249, 0.45)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.arc(mouse.x, mouse.y, FLEE_R, 0, Math.PI * 2);
        ctx.stroke();
      }
      raf = requestAnimationFrame(loop);
    };
    raf = requestAnimationFrame(loop);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      c.removeEventListener("mousemove", onMove);
      c.removeEventListener("mouseleave", onLeave);
      c.removeEventListener("click", onClick);
    };
  }, []);
  return /*#__PURE__*/React.createElement("div", {
    className: "pipeline-viz"
  }, /*#__PURE__*/React.createElement("canvas", {
    ref: canvasRef,
    className: "pipeline-canvas boids-canvas"
  }), /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail open"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-id",
    style: {
      color: "var(--cyan)",
      borderColor: "var(--cyan)"
    }
  }, "BOIDS \xB7 1987"), /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-title"
  }, "Reynolds flocking, live")), /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-desc"
  }, "Three rules \u2014 separation, alignment, cohesion \u2014 produce emergent group behavior. Every frame: O(N\xB2) neighbor query, three steering forces, speed cap, toroidal wrap. ", /*#__PURE__*/React.createElement("strong", {
    style: {
      color: "var(--ink)"
    }
  }, population), " agents, zero dependencies."), /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-body"
  }, /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--violet)"
    }
  }, "\u21B3"), " Move your cursor through the flock \u2014 boids flee a predator radius. ", /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--violet)"
    }
  }, "\u21B3"), " Click to fire a radial shockwave. ", /*#__PURE__*/React.createElement("span", {
    style: {
      color: "var(--ink-dim)"
    }
  }, "scatters:"), " ", /*#__PURE__*/React.createElement("strong", null, scatters))));
};

// Alias the old names so any stale references keep working
window.PipelineViz = window.BoidsGame;
window.SkillConstellation = window.BoidsGame;

// (legacy pipeline viz below — unused; kept so nothing silently breaks)
window.OldPipelineViz = () => {
  const canvasRef = React.useRef(null);
  const [pinnedId, setPinnedId] = React.useState(null);
  const [hoverId, setHoverId] = React.useState(null);
  const STAGES = window.PIPELINE || [];
  React.useEffect(() => {
    const c = canvasRef.current;
    if (!c) return;
    const ctx = c.getContext("2d");
    const resize = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      c.width = c.clientWidth * dpr;
      c.height = c.clientHeight * dpr;
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.scale(dpr, dpr);
    };
    resize();
    const ro = new ResizeObserver(resize);
    ro.observe(c);
    const W = () => c.clientWidth,
      H = () => c.clientHeight;

    // Lay nodes out as a horizontal pipeline, evenly spaced
    const nodeAt = i => {
      const w = W(),
        h = H();
      const margin = 40;
      const usable = w - margin * 2;
      const x = margin + usable * (STAGES.length === 1 ? 0.5 : i / (STAGES.length - 1));
      const y = h * 0.5;
      return {
        x,
        y
      };
    };

    // Particles flowing from stage to stage
    const particles = [];
    const spawnParticle = () => {
      particles.push({
        stage: 0,
        t: 0,
        speed: 0.35 + Math.random() * 0.4,
        // how fast it crosses one stage
        color: STAGES[0] ? STAGES[0].color : "#a78bfa"
      });
    };
    let lastSpawn = 0;

    // Mouse tracking
    const mouse = {
      x: -1e6,
      y: -1e6
    };
    let hoveredIdx = -1;
    const onMove = e => {
      const rect = c.getBoundingClientRect();
      mouse.x = e.clientX - rect.left;
      mouse.y = e.clientY - rect.top;
    };
    const onLeave = () => {
      mouse.x = mouse.y = -1e6;
    };
    const onClick = () => {
      if (hoveredIdx >= 0) {
        const id = STAGES[hoveredIdx].id;
        setPinnedId(prev => prev === id ? null : id);
      }
    };
    c.addEventListener("mousemove", onMove);
    c.addEventListener("mouseleave", onLeave);
    c.addEventListener("click", onClick);

    // --- Stage icon renderers — drawn inside the node. Each icon is a small
    // 20x20-ish canvas drawing that evokes its stage visually. ---
    const drawIcon = (x, y, type, color, alpha) => {
      ctx.save();
      ctx.translate(x, y);
      ctx.globalAlpha = alpha;
      ctx.strokeStyle = color;
      ctx.fillStyle = color;
      ctx.lineWidth = 1.4;
      if (type === "points") {
        // triangle of 3 points
        const r = 3;
        [[-7, -4], [7, -4], [0, 7]].forEach(([px, py]) => {
          ctx.beginPath();
          ctx.arc(px, py, r, 0, Math.PI * 2);
          ctx.fill();
        });
      } else if (type === "matrix") {
        // 3x3 grid of dots
        for (let ix = -1; ix <= 1; ix++) for (let iy = -1; iy <= 1; iy++) {
          ctx.beginPath();
          ctx.arc(ix * 6, iy * 6, 1.8, 0, Math.PI * 2);
          ctx.fill();
        }
      } else if (type === "triangle") {
        ctx.beginPath();
        ctx.moveTo(-9, 7);
        ctx.lineTo(9, 7);
        ctx.lineTo(0, -9);
        ctx.closePath();
        ctx.stroke();
      } else if (type === "grid") {
        // 4x4 pixel grid
        const s = 3,
          off = -6;
        for (let ix = 0; ix < 4; ix++) for (let iy = 0; iy < 4; iy++) {
          if ((ix + iy) % 2 === 0) {
            ctx.globalAlpha = alpha * 0.85;
            ctx.fillRect(off + ix * s, off + iy * s, s - 0.5, s - 0.5);
          }
        }
        ctx.globalAlpha = alpha;
      } else if (type === "shade") {
        // gradient-filled circle (lighting)
        const g = ctx.createRadialGradient(-3, -3, 1, 0, 0, 9);
        g.addColorStop(0, "#ffffff");
        g.addColorStop(1, color);
        ctx.fillStyle = g;
        ctx.beginPath();
        ctx.arc(0, 0, 8, 0, Math.PI * 2);
        ctx.fill();
      } else if (type === "screen") {
        // rectangle with a diagonal scanline — "framebuffer"
        ctx.strokeRect(-9, -6, 18, 12);
        ctx.beginPath();
        ctx.moveTo(-9, 6);
        ctx.lineTo(9, -6);
        ctx.stroke();
      }
      ctx.restore();
    };
    let raf;
    const loop = now => {
      const w = W(),
        h = H();
      const dt = 1 / 60;

      // Spawn particles on a rolling cadence
      if (now - lastSpawn > 420) {
        spawnParticle();
        lastSpawn = now;
      }

      // Advance particles
      for (let i = particles.length - 1; i >= 0; i--) {
        const p = particles[i];
        p.t += dt * p.speed;
        if (p.t >= 1) {
          p.stage++;
          p.t = 0;
          if (p.stage >= STAGES.length - 1) {
            particles.splice(i, 1);
            continue;
          }
          p.color = STAGES[p.stage].color;
        }
      }

      // Hover detection
      let nextHovered = -1;
      for (let i = 0; i < STAGES.length; i++) {
        const n = nodeAt(i);
        const dx = mouse.x - n.x,
          dy = mouse.y - n.y;
        if (dx * dx + dy * dy < 38 * 38) {
          nextHovered = i;
          break;
        }
      }
      if (nextHovered !== hoveredIdx) {
        hoveredIdx = nextHovered;
        setHoverId(nextHovered >= 0 ? STAGES[nextHovered].id : null);
      }

      // --- DRAW ---
      ctx.clearRect(0, 0, w, h);

      // Flow lines between stages
      ctx.lineWidth = 1;
      for (let i = 0; i < STAGES.length - 1; i++) {
        const a = nodeAt(i),
          b = nodeAt(i + 1);
        const g = ctx.createLinearGradient(a.x, 0, b.x, 0);
        g.addColorStop(0, STAGES[i].color + "66");
        g.addColorStop(1, STAGES[i + 1].color + "66");
        ctx.strokeStyle = g;
        ctx.beginPath();
        ctx.moveTo(a.x + 38, a.y);
        ctx.lineTo(b.x - 38, b.y);
        ctx.stroke();
        // Arrowhead
        ctx.fillStyle = STAGES[i + 1].color;
        ctx.beginPath();
        ctx.moveTo(b.x - 38, b.y);
        ctx.lineTo(b.x - 44, b.y - 4);
        ctx.lineTo(b.x - 44, b.y + 4);
        ctx.closePath();
        ctx.fill();
      }

      // Flowing particles along each segment
      for (const p of particles) {
        if (p.stage >= STAGES.length - 1) continue;
        const a = nodeAt(p.stage),
          b = nodeAt(p.stage + 1);
        const x = a.x + 38 + (b.x - 38 - (a.x + 38)) * p.t;
        const y = a.y;
        // trail
        const tailX = a.x + 38 + (b.x - 38 - (a.x + 38)) * Math.max(0, p.t - 0.18);
        const tg = ctx.createLinearGradient(tailX, y, x, y);
        tg.addColorStop(0, "rgba(255,255,255,0)");
        tg.addColorStop(1, p.color);
        ctx.strokeStyle = tg;
        ctx.lineWidth = 2.2;
        ctx.beginPath();
        ctx.moveTo(tailX, y);
        ctx.lineTo(x, y);
        ctx.stroke();
        ctx.fillStyle = p.color;
        ctx.shadowColor = p.color;
        ctx.shadowBlur = 8;
        ctx.beginPath();
        ctx.arc(x, y, 3, 0, Math.PI * 2);
        ctx.fill();
        ctx.shadowBlur = 0;
      }

      // Stage nodes
      for (let i = 0; i < STAGES.length; i++) {
        const n = nodeAt(i);
        const stage = STAGES[i];
        const isHover = i === hoveredIdx;
        const isPinned = stage.id === pinnedId;
        const isDimmed = pinnedId && !isPinned;
        const alpha = isDimmed ? 0.3 : 1;
        const baseR = 30;
        const r = baseR + (isHover || isPinned ? 6 : 0);

        // outer glow ring
        ctx.save();
        ctx.globalAlpha = alpha * (isHover || isPinned ? 0.9 : 0.6);
        ctx.shadowColor = stage.color;
        ctx.shadowBlur = isHover || isPinned ? 26 : 14;
        ctx.strokeStyle = stage.color;
        ctx.lineWidth = 1.8;
        ctx.beginPath();
        ctx.arc(n.x, n.y, r, 0, Math.PI * 2);
        ctx.stroke();
        ctx.shadowBlur = 0;
        // fill disc (darker)
        ctx.globalAlpha = alpha * 0.18;
        ctx.fillStyle = stage.color;
        ctx.beginPath();
        ctx.arc(n.x, n.y, r - 2, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();

        // icon
        drawIcon(n.x, n.y, stage.icon, stage.color, alpha);

        // stage number
        ctx.globalAlpha = alpha * 0.85;
        ctx.fillStyle = "rgba(231,233,255,0.6)";
        ctx.font = "700 10px JetBrains Mono, monospace";
        ctx.textAlign = "center";
        ctx.fillText(String(i + 1).padStart(2, "0"), n.x, n.y - r - 10);
        // stage label
        ctx.fillStyle = isHover || isPinned ? "#ffffff" : "rgba(231,233,255,0.82)";
        ctx.font = `${isHover || isPinned ? 600 : 500} 11px JetBrains Mono, monospace`;
        ctx.fillText(stage.name, n.x, n.y + r + 16);
        ctx.globalAlpha = 1;
        ctx.textAlign = "start";
      }
      raf = requestAnimationFrame(loop);
    };
    raf = requestAnimationFrame(loop);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      c.removeEventListener("mousemove", onMove);
      c.removeEventListener("mouseleave", onLeave);
      c.removeEventListener("click", onClick);
    };
  }, []);
  const focusStage = STAGES.find(s => s.id === (pinnedId || hoverId));
  return /*#__PURE__*/React.createElement("div", {
    className: "pipeline-viz"
  }, /*#__PURE__*/React.createElement("canvas", {
    ref: canvasRef,
    className: "pipeline-canvas"
  }), /*#__PURE__*/React.createElement("div", {
    className: `pipeline-detail ${focusStage ? "open" : ""}`
  }, focusStage ? /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-id",
    style: {
      color: focusStage.color,
      borderColor: focusStage.color
    }
  }, "STAGE ", String(STAGES.findIndex(s => s.id === focusStage.id) + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-title"
  }, focusStage.name), pinnedId === focusStage.id && /*#__PURE__*/React.createElement("button", {
    className: "pipeline-detail-close",
    onClick: () => setPinnedId(null)
  }, "unpin")), /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-desc"
  }, focusStage.desc), pinnedId === focusStage.id && /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-body"
  }, focusStage.detail), /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-skills"
  }, (focusStage.mySkills || []).map(s => /*#__PURE__*/React.createElement("span", {
    key: s,
    className: "pipeline-skill-chip",
    style: {
      borderColor: focusStage.color,
      color: focusStage.color
    }
  }, s))))) : /*#__PURE__*/React.createElement("div", {
    className: "pipeline-detail-hint"
  }, "[ hover a stage \xB7 click to pin ]")));
};

// Backwards-compat alias — anything still referencing SkillConstellation renders the pipeline.
window.SkillConstellation = window.PipelineViz;

// (legacy SkillConstellation follows below for reference but is overridden above)
window.OldSkillConstellation = () => {
  const ref = React.useRef(null);
  React.useEffect(() => {
    const c = ref.current;
    if (!c) return;
    const ctx = c.getContext("2d");
    const resize = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      c.width = c.clientWidth * dpr;
      c.height = c.clientHeight * dpr;
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.scale(dpr, dpr);
    };
    resize();
    const ro = new ResizeObserver(resize);
    ro.observe(c);
    const CATS = window.SKILLS && window.SKILLS.categories || [];
    const CONNS = window.SKILLS && window.SKILLS.connections || [];
    const GROUPS = window.SKILLS && window.SKILLS.groups || [];
    const W = () => c.clientWidth,
      H = () => c.clientHeight;

    // Derive a skill level (0..100) by fuzzy-matching the node name against
    // the entries in SKILLS.groups. Falls back to 75 if no match found.
    const levelFor = name => {
      for (const g of GROUPS) {
        for (const [k, lvl] of g.items) {
          if (k.toLowerCase().includes(name.toLowerCase()) || name.toLowerCase().includes(k.toLowerCase().split(/[\s/]+/)[0])) {
            return lvl;
          }
        }
      }
      return 75;
    };

    // Build nodes — each category laid out on a ring, skills orbiting its center.
    const nodes = [];
    CATS.forEach((cat, ci) => {
      const ang0 = ci / CATS.length * Math.PI * 2 - Math.PI / 2;
      cat.skills.forEach((s, i) => {
        const ringAng = i / cat.skills.length * Math.PI * 2 + ci * 0.4;
        nodes.push({
          id: nodes.length,
          name: s,
          cat: ci,
          color: cat.color,
          level: levelFor(s),
          // Home position in normalized (0..1) coordinates — recomputed on resize
          hx: 0.5 + Math.cos(ang0) * 0.28 + Math.cos(ringAng) * 0.11,
          hy: 0.5 + Math.sin(ang0) * 0.28 + Math.sin(ringAng) * 0.11,
          x: 0,
          y: 0,
          // pixel-space (resolved from hx/hy each frame)
          energy: 0,
          // 0..1 activation — spikes when a pulse arrives or on hover
          phase: Math.random() * Math.PI * 2 // for per-node breathing offset
        });
      });
    });

    // Node lookup by name (case-insensitive)
    const nodeByName = {};
    nodes.forEach(n => {
      nodeByName[n.name.toLowerCase()] = n;
    });

    // Build edges: same-category + explicit cross-category pairs
    const edges = [];
    const edgeSet = new Set();
    const addEdge = (a, b, cross = false) => {
      const k = a < b ? `${a}-${b}` : `${b}-${a}`;
      if (edgeSet.has(k)) return;
      edgeSet.add(k);
      edges.push({
        a,
        b,
        cross
      });
    };
    // Intra-category
    for (let i = 0; i < nodes.length; i++) {
      for (let j = i + 1; j < nodes.length; j++) {
        if (nodes[i].cat === nodes[j].cat) addEdge(i, j, false);
      }
    }
    // Cross-category
    CONNS.forEach(([n1, n2]) => {
      const a = nodeByName[n1.toLowerCase()];
      const b = nodeByName[n2.toLowerCase()];
      if (a && b) addEdge(a.id, b.id, a.cat !== b.cat);
    });

    // Adjacency lookup — neighbors[i] = array of node ids connected to i
    const neighbors = nodes.map(() => []);
    edges.forEach(({
      a,
      b
    }) => {
      neighbors[a].push(b);
      neighbors[b].push(a);
    });

    // Pulses — light particles traveling from->to along an edge, fading over time.
    const pulses = [];
    const firePulse = (from, to, strength = 1) => {
      pulses.push({
        from,
        to,
        t: 0,
        life: 0.9,
        strength,
        color: nodes[from].color
      });
    };
    const fireBurst = (idx, strength = 1) => {
      nodes[idx].energy = Math.min(1, nodes[idx].energy + 0.6 * strength);
      neighbors[idx].forEach(ni => firePulse(idx, ni, strength));
    };

    // Mouse / hover / pin state
    const mouse = {
      x: -1e6,
      y: -1e6
    };
    let hovered = -1;
    let pinned = -1;
    let lastHoverFire = 0;
    const onMove = e => {
      const rect = c.getBoundingClientRect();
      mouse.x = e.clientX - rect.left;
      mouse.y = e.clientY - rect.top;
    };
    const onLeave = () => {
      mouse.x = mouse.y = -1e6;
    };
    const onClick = () => {
      pinned = pinned === hovered ? -1 : hovered;
    };
    c.addEventListener("mousemove", onMove);
    c.addEventListener("mouseleave", onLeave);
    c.addEventListener("click", onClick);

    // Auto-fire scheduler
    let nextAutoFire = performance.now() + 1500;
    let raf,
      last = performance.now();
    const loop = now => {
      const dt = Math.min(0.05, (now - last) / 1000);
      last = now;
      const w = W(),
        h = H();

      // Resolve home positions to pixel coords
      nodes.forEach(n => {
        n.x = n.hx * w;
        n.y = n.hy * h;
      });

      // Hover detection — pick nearest node within 24px
      let bestDist = 24 * 24,
        bestIdx = -1;
      for (let i = 0; i < nodes.length; i++) {
        const dx = mouse.x - nodes[i].x,
          dy = mouse.y - nodes[i].y;
        const d2 = dx * dx + dy * dy;
        if (d2 < bestDist) {
          bestDist = d2;
          bestIdx = i;
        }
      }
      hovered = bestIdx;

      // On-hover: fire pulses at most every 220ms (so it throbs, doesn't flood)
      if (hovered >= 0 && now - lastHoverFire > 220) {
        fireBurst(hovered, 1);
        lastHoverFire = now;
      }

      // Auto-fire: pick a random node and burst from it
      if (now > nextAutoFire) {
        const idx = Math.floor(Math.random() * nodes.length);
        fireBurst(idx, 0.6);
        nextAutoFire = now + 1400 + Math.random() * 1500;
      }

      // Decay energy
      nodes.forEach(n => {
        n.energy = Math.max(0, n.energy - dt * 1.1);
      });

      // Dim factor — non-pinned, non-neighbors of pinned node are dimmed
      const pinnedNeighbors = pinned >= 0 ? new Set([pinned, ...neighbors[pinned]]) : null;
      const dimOf = i => pinned < 0 || pinnedNeighbors && pinnedNeighbors.has(i) ? 1 : 0.22;

      // --- DRAW ---
      ctx.clearRect(0, 0, w, h);

      // Edges (base layer) — cross-category slightly brighter than intra
      for (const e of edges) {
        const a = nodes[e.a],
          b = nodes[e.b];
        const dimA = dimOf(e.a),
          dimB = dimOf(e.b);
        const dim = Math.min(dimA, dimB);
        const alpha = (e.cross ? 0.22 : 0.13) * dim;
        ctx.strokeStyle = e.cross ? `rgba(231, 233, 255, ${alpha})` : `rgba(167, 139, 250, ${alpha})`;
        ctx.lineWidth = e.cross ? 0.9 : 0.55;
        ctx.beginPath();
        ctx.moveTo(a.x, a.y);
        ctx.lineTo(b.x, b.y);
        ctx.stroke();
      }

      // Pulses — update position, render a short bright trail along the edge
      for (let pi = pulses.length - 1; pi >= 0; pi--) {
        const p = pulses[pi];
        p.t += dt / p.life;
        if (p.t >= 1) {
          // Arrived at target → briefly energize it
          nodes[p.to].energy = Math.min(1, nodes[p.to].energy + 0.35 * p.strength);
          pulses.splice(pi, 1);
          continue;
        }
        const a = nodes[p.from],
          b = nodes[p.to];
        const x = a.x + (b.x - a.x) * p.t;
        const y = a.y + (b.y - a.y) * p.t;
        // Trail
        const tailT = Math.max(0, p.t - 0.15);
        const tx = a.x + (b.x - a.x) * tailT;
        const ty = a.y + (b.y - a.y) * tailT;
        const grad = ctx.createLinearGradient(tx, ty, x, y);
        grad.addColorStop(0, "rgba(255,255,255,0)");
        grad.addColorStop(1, p.color);
        ctx.strokeStyle = grad;
        ctx.lineWidth = 2.2 * p.strength;
        ctx.beginPath();
        ctx.moveTo(tx, ty);
        ctx.lineTo(x, y);
        ctx.stroke();
        // Head
        ctx.fillStyle = p.color;
        ctx.globalAlpha = 0.95 * p.strength;
        ctx.beginPath();
        ctx.arc(x, y, 3.2 * p.strength, 0, Math.PI * 2);
        ctx.fill();
        ctx.globalAlpha = 1;
      }

      // Nodes — radius from level + energy, glow scales with energy
      for (let i = 0; i < nodes.length; i++) {
        const n = nodes[i];
        const isHover = i === hovered;
        const isPinned = i === pinned;
        const dim = dimOf(i);
        const breath = 1 + Math.sin(now * 0.002 + n.phase) * 0.06;
        const baseR = (3 + (n.level - 60) * 0.18) * breath;
        const r = baseR * (1 + n.energy * 0.8) * (isHover || isPinned ? 1.35 : 1);
        const glow = 6 + 22 * n.energy + (isHover ? 16 : 0);

        // Outer glow
        ctx.shadowColor = n.color;
        ctx.shadowBlur = glow * dim;
        ctx.fillStyle = n.color;
        ctx.globalAlpha = dim;
        ctx.beginPath();
        ctx.arc(n.x, n.y, r, 0, Math.PI * 2);
        ctx.fill();
        ctx.shadowBlur = 0;

        // Inner core dot
        ctx.fillStyle = "#ffffff";
        ctx.globalAlpha = dim * (0.35 + n.energy * 0.6);
        ctx.beginPath();
        ctx.arc(n.x, n.y, Math.max(1, r * 0.4), 0, Math.PI * 2);
        ctx.fill();
        ctx.globalAlpha = 1;

        // Label — always on; size/weight amplifies when active
        const amp = isHover || isPinned ? 1 : 0.7 + n.energy * 0.4;
        ctx.fillStyle = `rgba(231,233,255,${dim * Math.min(1, 0.55 + n.energy * 0.6 + (isHover || isPinned ? 0.45 : 0))})`;
        ctx.font = `${isHover || isPinned ? 700 : 500} ${10 + (isHover || isPinned ? 2 : 0)}px JetBrains Mono, monospace`;
        ctx.fillText(n.name, n.x + r + 5, n.y + 3 + amp * 1);
      }
      raf = requestAnimationFrame(loop);
    };
    raf = requestAnimationFrame(loop);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      c.removeEventListener("mousemove", onMove);
      c.removeEventListener("mouseleave", onLeave);
      c.removeEventListener("click", onClick);
    };
  }, []);
  const CATS = window.SKILLS && window.SKILLS.categories || [];
  return /*#__PURE__*/React.createElement("div", {
    className: "skill-constellation"
  }, /*#__PURE__*/React.createElement("canvas", {
    ref: ref
  }), /*#__PURE__*/React.createElement("div", {
    className: "skill-legend"
  }, CATS.map(c => /*#__PURE__*/React.createElement("div", {
    key: c.name
  }, /*#__PURE__*/React.createElement("span", {
    className: "skill-legend-dot",
    style: {
      background: c.color
    }
  }), c.name))), /*#__PURE__*/React.createElement("div", {
    className: "skill-caption"
  }, "[ hover a node to fire \xB7 click to pin ]"));
};
window.Skills = () => {
  const GROUPS = window.SKILLS && window.SKILLS.groups || [];
  return /*#__PURE__*/React.createElement("section", {
    className: "skills",
    id: "skills",
    "data-screen-label": "skills"
  }, /*#__PURE__*/React.createElement("div", {
    className: "skills-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "section-label"
  }, /*#__PURE__*/React.createElement("span", {
    className: "section-num"
  }, "04"), " skills \xB7 live demo"), /*#__PURE__*/React.createElement("h2", {
    className: "section-head"
  }, "180 boids.", /*#__PURE__*/React.createElement("br", null), "Three rules."), /*#__PURE__*/React.createElement("p", {
    className: "section-sub"
  }, "A live Reynolds flocking simulation \u2014 one of the foundational algorithms of real-time graphics. Move your cursor through the flock. Click to scatter them. Supporting skill levels below.")), /*#__PURE__*/React.createElement("div", {
    className: "skills-layout pipeline-layout"
  }, /*#__PURE__*/React.createElement(window.BoidsGame, null), /*#__PURE__*/React.createElement("div", {
    className: "skill-table"
  }, GROUPS.map(g => /*#__PURE__*/React.createElement("div", {
    key: g.title
  }, /*#__PURE__*/React.createElement("div", {
    className: "skill-group-title"
  }, g.title), g.items.map(([name, lvl]) => /*#__PURE__*/React.createElement("div", {
    key: name,
    className: "skill-row"
  }, /*#__PURE__*/React.createElement("div", {
    className: "skill-name"
  }, name), /*#__PURE__*/React.createElement("div", {
    className: "skill-bar",
    style: {
      "--lvl": lvl + "%"
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "skill-lvl"
  }, lvl))))))));
};

// ---------- EXPERIENCE ----------
window.Experience = () => {
  const XP = window.EXPERIENCE || [];
  return /*#__PURE__*/React.createElement("section", {
    className: "xp",
    id: "experience",
    "data-screen-label": "experience"
  }, /*#__PURE__*/React.createElement("div", {
    className: "xp-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "section-label"
  }, /*#__PURE__*/React.createElement("span", {
    className: "section-num"
  }, "05"), " experience"), /*#__PURE__*/React.createElement("h2", {
    className: "section-head"
  }, "Founder, engineer,", /*#__PURE__*/React.createElement("br", null), "and graduate.")), /*#__PURE__*/React.createElement("div", {
    className: "xp-timeline"
  }, XP.map((item, i) => /*#__PURE__*/React.createElement("div", {
    key: i,
    className: `xp-item ${item.type === "research" ? "research" : item.type === "edu" ? "edu" : ""}`
  }, /*#__PURE__*/React.createElement("div", {
    className: "xp-date"
  }, item.date), /*#__PURE__*/React.createElement("div", {
    className: "xp-role"
  }, item.role), /*#__PURE__*/React.createElement("div", {
    className: "xp-org"
  }, item.org), /*#__PURE__*/React.createElement("div", {
    className: "xp-bullets"
  }, item.bullets.map((b, bi) => /*#__PURE__*/React.createElement("div", {
    key: bi,
    className: "xp-bullet"
  }, b))), item.img && /*#__PURE__*/React.createElement("div", {
    className: "xp-img"
  }, /*#__PURE__*/React.createElement("img", {
    src: item.img,
    alt: item.role
  }))))));
};

// ---------- RESEARCH ----------
window.Research = () => /*#__PURE__*/React.createElement("section", {
  className: "research",
  id: "research",
  "data-screen-label": "research"
}, /*#__PURE__*/React.createElement("div", {
  className: "section-label"
}, /*#__PURE__*/React.createElement("span", {
  className: "section-num"
}, "06"), " research"), /*#__PURE__*/React.createElement("h2", {
  className: "section-head",
  style: {
    marginBottom: 40
  }
}, "Spacecraft cables,", /*#__PURE__*/React.createElement("br", null), "six degrees of freedom."), /*#__PURE__*/React.createElement("div", {
  className: "research-card"
}, /*#__PURE__*/React.createElement("div", {
  className: "research-media"
}, /*#__PURE__*/React.createElement("img", {
  src: "assets/projects/spaceSim.png",
  alt: "SPACESiM"
})), /*#__PURE__*/React.createElement("div", {
  className: "research-body"
}, /*#__PURE__*/React.createElement("div", {
  className: "research-collab"
}, "UMN \xD7 Cornell University \xB7 funded"), /*#__PURE__*/React.createElement("h3", {
  className: "research-title"
}, "Cable-Driven 6-DoF Spacecraft Motion Simulator"), /*#__PURE__*/React.createElement("p", {
  className: "research-desc"
}, "A real-time simulator modeling a payload moving in 6 degrees of freedom, suspended by 8 independently-tensioned cables. Hooke's-Law-based tension, recoil, and stretch give physically-accurate behavior for simulated docking-mission planning, so Cornell researchers can test models and mechanisms in-silico before touching hardware."), /*#__PURE__*/React.createElement("div", {
  className: "research-stats"
}, /*#__PURE__*/React.createElement("div", {
  className: "research-stat"
}, /*#__PURE__*/React.createElement("div", {
  className: "research-stat-v"
}, "6"), /*#__PURE__*/React.createElement("div", {
  className: "research-stat-k"
}, "degrees of freedom")), /*#__PURE__*/React.createElement("div", {
  className: "research-stat"
}, /*#__PURE__*/React.createElement("div", {
  className: "research-stat-v"
}, "8"), /*#__PURE__*/React.createElement("div", {
  className: "research-stat-k"
}, "independent cables")), /*#__PURE__*/React.createElement("div", {
  className: "research-stat"
}, /*#__PURE__*/React.createElement("div", {
  className: "research-stat-v"
}, "UE5"), /*#__PURE__*/React.createElement("div", {
  className: "research-stat-k"
}, "real-time engine"))))));

// ---------- CONTACT ----------
window.Contact = () => /*#__PURE__*/React.createElement("section", {
  className: "contact",
  id: "contact",
  "data-screen-label": "contact"
}, /*#__PURE__*/React.createElement("div", {
  className: "contact-inner"
}, /*#__PURE__*/React.createElement("div", null, /*#__PURE__*/React.createElement("div", {
  className: "section-label"
}, /*#__PURE__*/React.createElement("span", {
  className: "section-num"
}, "07"), " contact"), /*#__PURE__*/React.createElement("h2", {
  className: "contact-big"
}, "Let's build ", /*#__PURE__*/React.createElement("span", {
  className: "accent"
}, "something"), "."), /*#__PURE__*/React.createElement("a", {
  className: "contact-email",
  href: "mailto:brnolson33@gmail.com"
}, "brnolson33@gmail.com", /*#__PURE__*/React.createElement("span", {
  style: {
    color: "var(--violet)"
  }
}, "\u2192")), /*#__PURE__*/React.createElement("div", {
  className: "contact-links"
}, /*#__PURE__*/React.createElement("a", {
  className: "contact-link",
  href: "https://github.com/brnolson",
  target: "_blank",
  rel: "noreferrer"
}, /*#__PURE__*/React.createElement("span", {
  className: "contact-link-k"
}, "github"), /*#__PURE__*/React.createElement("span", null, "brnolson"), /*#__PURE__*/React.createElement("span", {
  className: "contact-link-arrow"
}, "\u2197")), /*#__PURE__*/React.createElement("a", {
  className: "contact-link",
  href: "https://www.linkedin.com/in/brenen-olson/",
  target: "_blank",
  rel: "noreferrer"
}, /*#__PURE__*/React.createElement("span", {
  className: "contact-link-k"
}, "linkedin"), /*#__PURE__*/React.createElement("span", null, "brenen-olson"), /*#__PURE__*/React.createElement("span", {
  className: "contact-link-arrow"
}, "\u2197")), /*#__PURE__*/React.createElement("a", {
  className: "contact-link",
  href: "mailto:brnolson33@gmail.com"
}, /*#__PURE__*/React.createElement("span", {
  className: "contact-link-k"
}, "email"), /*#__PURE__*/React.createElement("span", null, "brnolson33@gmail.com"), /*#__PURE__*/React.createElement("span", {
  className: "contact-link-arrow"
}, "\u2197")))), /*#__PURE__*/React.createElement("form", {
  className: "contact-form",
  action: "https://formspree.io/f/mldgnwgw",
  method: "POST"
}, /*#__PURE__*/React.createElement("label", {
  htmlFor: "email"
}, "your email"), /*#__PURE__*/React.createElement("input", {
  type: "email",
  id: "email",
  name: "email",
  required: true,
  placeholder: "you@example.com"
}), /*#__PURE__*/React.createElement("label", {
  htmlFor: "message"
}, "message"), /*#__PURE__*/React.createElement("textarea", {
  id: "message",
  name: "message",
  rows: "6",
  required: true,
  placeholder: "hey brenen \u2014 I'd love to talk about..."
}), /*#__PURE__*/React.createElement("button", {
  type: "submit",
  className: "cta primary",
  style: {
    alignSelf: "flex-start"
  }
}, "send message \u2192"))));

// ---------- KONAMI ----------
window.Konami = () => {
  const [active, setActive] = React.useState(false);
  React.useEffect(() => {
    const code = ["ArrowUp", "ArrowUp", "ArrowDown", "ArrowDown", "ArrowLeft", "ArrowRight", "ArrowLeft", "ArrowRight", "b", "a"];
    let idx = 0;
    const onKey = e => {
      const k = e.key;
      if (k.toLowerCase() === code[idx].toLowerCase() || k === code[idx]) {
        idx++;
        if (idx === code.length) {
          setActive(true);
          idx = 0;
        }
      } else {
        idx = k === code[0] ? 1 : 0;
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, []);
  if (!active) return null;
  return /*#__PURE__*/React.createElement("div", {
    className: `konami-overlay ${active ? "active" : ""}`
  }, /*#__PURE__*/React.createElement("div", {
    className: "konami-terminal"
  }, /*#__PURE__*/React.createElement("button", {
    className: "konami-close",
    onClick: () => setActive(false)
  }, "[ esc ]"), /*#__PURE__*/React.createElement("pre", {
    style: {
      whiteSpace: "pre-wrap",
      lineHeight: 1.6
    }
  }, `> ACCESS GRANTED — brenen.olson:root
> loading .bio...

  name       Brenen Olson
  role       graphics engineer
  mission    build graphics at the edge of reality
  secret     this portfolio is itself a graphics demo

> fun facts:
  • 320-member marching band trombone section lead
  • shipped wedding app w/ real auth on Cloudflare + Supabase
  • named a chaos mode "SAVE YOUR GPU"

> type 'hire' to hire me.

`)));
};
