#!/usr/bin/env node
// Compile the four .jsx source files under js/ into plain .js that browsers can
// load directly (no Babel-in-browser, no CORS fetch). Run `node compile.cjs`
// after editing any .jsx file. Data file (js/data.js) does not need compilation.

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const CACHE = path.join(__dirname, ".babel-cache");
const BABEL_PATH = path.join(CACHE, "node_modules", "@babel", "standalone");
if (!fs.existsSync(BABEL_PATH)) {
  fs.mkdirSync(CACHE, { recursive: true });
  // Ensure a minimal package.json exists so npm doesn't complain
  const pkgPath = path.join(CACHE, "package.json");
  if (!fs.existsSync(pkgPath)) fs.writeFileSync(pkgPath, JSON.stringify({ name: "babel-cache", version: "1.0.0", private: true }));
  console.log("Installing @babel/standalone (one-time, ~20MB)…");
  execSync("npm install --no-save --silent --no-audit --no-fund @babel/standalone", { cwd: CACHE, stdio: "inherit", shell: true });
}
const Babel = require(BABEL_PATH);

const FILES = [
  "js/hero-orb.jsx",
  "js/pin-scene.jsx",
  "js/sections.jsx",
  "js/bootstrap.jsx",
];

let ok = 0, fail = 0;
for (const f of FILES) {
  try {
    const src = fs.readFileSync(f, "utf8");
    const { code } = Babel.transform(src, { presets: ["react"] });
    const out = f.replace(/\.jsx$/, ".js");
    fs.writeFileSync(out, `// AUTO-GENERATED by compile.cjs from ${path.basename(f)} — do not edit by hand.\n${code}\n`);
    console.log(`  ${f}  →  ${out}`);
    ok++;
  } catch (e) {
    console.error(`  FAIL ${f}: ${e.message}`);
    fail++;
  }
}
console.log(`\nCompiled ${ok} file(s), ${fail} failed.`);
process.exit(fail ? 1 : 0);
